### PR TITLE
Use trailing commas when printing multiline JS objects

### PR DESCRIPTION
**Pull request by hustLer2k**
### What does this PR do?

This PR implements https://github.com/oven-sh/bun/issues/7262

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [✓ ] Code changes

### How did you verify your code works?

- [ ✓] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [✓ ] I included a test for the new code, or an existing test covers it
- [✓ ] JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed
- [ ✓] I wrote TypeScript/JavaScript tests and they pass locally (`bun-debug test test-file-name.test`)

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
Thank you for this. There probably will be some tests to update. I'm not totally confident this will cover every case (such as when there is only one object to print)

**Comment by hustLer2k** [comment]
Could you suggest where the related tests are located?

**Review by paperclover — CHANGES_REQUESTED** [review]
looks great. there are more test failures. all of these are going to be fixing the test to match the new output. after that this can be merged.

one test failure:

image

**Comment by paperclover** [comment]
list of failing test files to check for, some of these might just be known flaky tests:
  
  - `test/js/bun/test/test-test.test.ts`
  - `test/js/bun/util/inspect.test.js`
  - `test/js/node/util/bun-inspect.test.ts`
  - `test/js/node/util/custom-inspect.test.js`
  - `test/js/web/fetch/headers.test.ts`
  - `test/js/web/html/URLSearchParams.test.ts`
  - `test/js/web/url/url.test.ts`
  - `test/transpiler/property.test.ts`

**Review by paperclover — APPROVED** [review]
great.

**Pull request merged**
