### PR TITLE
fix(cli): `bun pm cache rm` command not work

### PR DESCRIPTION
**Pull request by WingLim**
### What does this PR do?

Resolves https://github.com/oven-sh/bun/issues/1720

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

Compile and execute `bun pm cache rm`

### CODE REVIEW

**Comment by paperclover** [comment]
thanks for the pr!

could you write a test that uses `Bun.spawn` and the `BUN_INSTALL_CACHE_DIR` environment variable to make sure this works and doesn't break later?

**Comment by WingLim** [comment]
@paperdave Test added.

**Review by paperclover — APPROVED** [review]

**Comment by paperclover** [comment]
thank you (sorry for the delay)

**Comment by elvisisvan** [comment]
### well...
image

**Comment by maiquealmeida** [comment]
> ### well...
> image

@elvisisvan did you try using with -f param to force exec?

```
bun pm cache rm -g -f
```

**Pull request merged**
