### PR TITLE
[misc] Add commit hooks to format files

### PR DESCRIPTION
**Pull request by jameslahm**

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
I'm wary of adding anything that slows down running `git commit`

I suggest configuring your editor to run `zig fmt` and `prettier` on save. This should be configured by default for VSCode (due to `./vscode/settings.json`)

What editor do you use? I wonder if there's a way to make it "just work" for your editor too

**Comment by Jarred-Sumner** [comment]
Ah, I didn't actually set it fully in `.vscode/settings.json`

I updated it so it should recommend now

**Comment by jameslahm** [comment]
I also use `vscode`. And It's sure that the changed files will be formated on save with `vscode` setup. But I afraid that the changes are not guaranteed to be well formated in the PRs. With these commit hooks, we can ensure that the files are well formated in every commit. WDYT? Also, I'd be happy to close it.

**Comment by Jarred-Sumner** [comment]
>  With these commit hooks, we can ensure that the files are well formated in every commit. 

I agree it would be better to have it, but I don't think it's worth it to add husky or depend on `npx` right now

Maybe once bun gets an equivalent to `child_process`, we could have a bun version that starts faster 😄 

The important part of the business logic in `lint-staged` is here:

https://github.com/okonet/lint-staged/blob/1b1f0e4f529dbcb5f73ab7d49c5f7908c3b8a866/lib/getStagedFiles.js#L12

It runs: `git diff --staged --diff-filter=ACMR --name-only  -z`
image

**Comment by jameslahm** [comment]
Yeah, agree. We could have a faster bun version 😄 . Close it now.

**Pull request closed without merging**
