### PR TITLE
update ffi.zig for dlopen

### PR DESCRIPTION
**Pull request by EzraEllette**
### What does this PR do?

The changes fix a bug where `dlopen` is not working in `bun:ffi`. Without these changes, attempts to use the function will result in an undefined error, and no real errors can propagate.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

- [ ] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [x] I or my editor ran `zig fmt` on the changed files
- [x]  I included a test for the new code, or an existing test covers it
- [ ] JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed

### CODE REVIEW

**Comment by EzraEllette** [comment]
https://github.com/oven-sh/bun/issues/5460

**Comment by paperclover** [comment]
these tests already pass in the current canary. the change does not change any logic

**Comment by EzraEllette** [comment]
> these tests already pass in the current canary. the change does not change any logic

Then your canary is broken.

**Comment by EzraEllette** [comment]
The issue it no longer present in 1.0.3

**Pull request closed without merging**
