### PR TITLE
Support reading from `$HOME/.npmrc`

### LINKED ISSUE #13764: Bun does not read from $HOME/.npmrc if it exists
### What version of Bun is running?

 v1.1.26-canary.13 (8d34846d)

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

create a ~/.npmrc with a different registry, that registry will not be respected during a `bun add`

### What is the expected behavior?

Bun can correctly read from project specific .npmrc files, so it should also read from the home directory too.

### What do you see instead?

The global .npmrc is ignored.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by robertshuford**
### What does this PR do?

This builds upon the work done in https://github.com/oven-sh/bun/pull/11979 by adding support for `$HOME/.npmrc`.
Settings in `./.npmrc` will override settings in `$HOME/.npmrc`.

- [x] Code changes

### How did you verify your code works?

I wrote automated tests

- [x] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [x] I included a test for the new code, or an existing test covers it
- [x] I wrote TypeScript/JavaScript tests and they pass locally (`bun-debug test test-file-name.test`)

resolves #13764

### CODE REVIEW

**Comment by robertshuford** [comment]
closes #13764

**Comment by chevcast** [comment]
Can't wait for this to merge. Will make our workflow so much easier since `aws codeartifact login --tool npm` insists on only generating a `.npmrc` in the `$HOME` directory.

**Review by dylan-conway — APPROVED** [review]
Looks great, thanks!

**Comment by dylan-conway** [comment]
Tested locally, going to merge

**Comment by lenovouser** [comment]
This does not seem to work for me with a global config like this:

```
@slug:registry=https://my-registry.tld/
//npm.panascais.net/:_authToken="<token>"
```

and a project config like this:

```
@slug:registry=https://my-registry.tld/

https://my-registry.tld/:always-auth=true

auto-install-peers=true
engine-strict=true
prefer-frozen-lockfile=true
resolution-mode=highest
save-exact=true
save-prefix=''
strict-peer-dependencies=true
update-notifier=true
```

I am on macOS.

**Comment by dylan-conway** [comment]
@lenovouser is it using the wrong registry for the `@slug` scope? Could you open a new issue?

**Comment by lenovouser** [comment]
@dylan-conway no, it doesn't use the auth token I believe.

https://github.com/oven-sh/bun/issues/14433

**Comment by VanTigranyan** [comment]
> This does not seem to work for me with a global config like this:
> 
> ```
> @slug:registry=https://my-registry.tld/
> //my-registry.tld/:_authToken="<token>"
> ```
> 
> and a project config like this:
> 
> ```
> @slug:registry=https://my-registry.tld/
> 
> https://my-registry.tld/:always-auth=true
> 
> auto-install-peers=true
> engine-strict=true
> prefer-frozen-lockfile=true
> resolution-mode=highest
> save-exact=true
> save-prefix=''
> strict-peer-dependencies=true
> update-notifier=true
> ```
> 
> I am on macOS.

Second this. In my case //my-registry.tld/:_auth="<token>". We use JFrog. I tried many things I even converted npmrc to bunfig.toml, nothing works. Bun basically doesn't work with JFrog.

**Comment by rdanilin** [comment]
I have an issue with `~/.npmrc` on my machine. bun is not loading it until I copy this file to the application folder. 
I'm using MacOS 26. Everything works fine inside Ubuntu Docker image. 

Do you have any suggestion how I can troubleshot it?

**Pull request merged**
