### PR TITLE
[WIP] fix(node:fs): export `fs.ReadStream` and `fs.WriteStream`

### LINKED ISSUE #1797: `fs.WriteStream` is undefined
### What version of Bun is running?

0.4.0

### What platform is your computer?

Darwin 20.6.0 x86_64 i386

### What steps can reproduce the bug?

I found that `formidable` uses `fs.WriteStream` but bun does not expose that, e.g. in `bunx bun-repl`

```js
import * as fs from 'node:fs';
console.log(fs.WriteStream); // undefined
```

I was having the error `TypeError: undefined is not a constructor (evaluating 'new fs.WriteStream(this.filepath)')` so I decided to patch the module:

```js
formidable.PersistentFile.prototype.open = function open() {
  this._writeStream = fs.createWriteStream(this.filepath);
  this._writeStream.on('error', err => {
    this.emit('error', err);
  });
};
```

This works, but now under certain cases (e.g. sending json) it complains with another error, see: https://github.com/oven-sh/bun/issues/1757

### What is the expected behavior?

The `fs.WriteStream` should return something, to avoid monkey-patching.

### What do you see instead?

An error, as I described above.

### Additional information

Well, bun is awesome, thank you! I am really having fun with. :)

### PR DESCRIPTION
**Pull request by ThatOneBro**
Fixes #1797 and adds a few tests

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
Can you add a test that checks if it works when using export from and export * from? Wondering what the compiler will do

**Comment by ThatOneBro** [comment]
> Can you add a test that checks if it works when using export from and export * from? Wondering what the compiler will do

Ah you're right, compiler doesn't like this. Is there any workaround that you can think of?

`SyntaxError: Import named 'ReadStream' not found in module '/Users/derrick/repos/bun-stuff/new/bun/test/fixtures/export-lazy-fs-streams/export-*-from.ts'.`

and 

`SyntaxError: Indirectly exported binding name 'ReadStream' is not found.`

**Comment by ThatOneBro** [comment]
Ok maybe this isn't worth it, but we could potentially create stub class functions that when constructed lazy load the real `ReadStream` or `WriteStream`, so the classes can be loaded without `node:stream` initially, even in the case where they are re-exported. It would fail an `instanceof` check, but maybe we can do something clever like the trick used for constructors without new.

Does that make sense at all?

**Comment by ThatOneBro** [comment]
Oops, just realized I made a noob mistake with the `Symbol.hasInstance` comparison lol

**Comment by ThatOneBro** [comment]
Update: `fs.ReadStream !== reexportedReadStream // result: true` when it should be false. Need another solution, possibly make every instance of `fs.ReadStream` a wrapper and at the time of construction of the first instance, load `node:stream` and patch the prototype chain of `fs.ReadStream` and the instance with the newly loaded `NativeReadable` subclass. Or we can abandon lazy-loading altogether. But that is costly to startup times as `node:stream` is very heavy...

**Comment by Jarred-Sumner** [comment]
Thank you

**Pull request merged**
