### PR TITLE
fix-262-missing-favicon

### LINKED ISSUE #262: Website has no icon
It would be nice to add the new Bun logo as a favicon

Screenshot from 2022-07-06 10-31-18

### PR DESCRIPTION
**Pull request by logikaljay**
fix: add the favicon. fixes #262

### CODE REVIEW

**Comment by logikaljay** [comment]
The logo (`public/logo@2x.png`) wasn't high enough resolution to generate a decent hi-res icon so I ran it through an image up-scaler.

Here is the upscaled result image:
bun-upscaled

**Review by hebertcisco — APPROVED** [review]

**Review by MatchaOnMuffins — APPROVED** [review]

**Comment by moderation** [comment]
It would be really good to have a SVG version of the logo too. I ran the existing logo through some converters and got some decent results. It would be nice for the upscaled imaged above to have a nice rounded right hand side versus the vertical line cutoff too

**Comment by logikaljay** [comment]
I agree on the SVG. 

Unfortuantely the source `logo@2x.png` file I had to work with has this cut off on it.

**Review by michellbrito — CHANGES_REQUESTED** [review]
@logikaljay Lets not edit the index.html page instead edit the `page.tsx` file. Also since this pr is adding the favicon are the css changes required?

**Comment by logikaljay** [comment]
Hey @michellbrito

The CSS changes were merged from upstream. I think this happened because my fork was out of date when I opened the PR. I am happy to clean it up if you think its required.

Regarding the index.html, I was unsure of any build step that may or may not happen where the landing page is hosted, as the built index.html file is committed to version control, I thought it would be best to include the changes there as well, in case the hosting is just static files and does not include a build step.

If the hosting does include a build step, I am happy to make additional changes to remove the index.html from version control.

**Pull request closed without merging**
