### PR TITLE
forward IPC to child process if running package script

### PR DESCRIPTION
**Pull request by snoglobe**
### What does this PR do?

fixes https://github.com/oven-sh/bun/issues/11132 which describes an issue where the file descriptor for ipc isn't being passed to the child process when spawning package scripts

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

I wrote automated tests

If Zig files changed:

- [x] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [x] I included a test for the new code, or an existing test covers it
- [ ] JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed
- [x] I wrote TypeScript/JavaScript tests and they pass locally (`bun-debug test test-file-name.test`)

### CODE REVIEW

**Comment by robobun** [comment]
@snoglobe, your commit bb88615a179559d71456984778638c9f22d2d128 is building: [`#3443`](https://buildkite.com/bun/bun/builds/3443)

**Comment by snoglobe** [comment]
accidentally added all prev commits - disregard all except the newest one

**Review by Jarred-Sumner — APPROVED** [review]

**Comment by Jarred-Sumner** [comment]
Looks like the Windows build failed

**Comment by snoglobe** [comment]
windows passes now

**Comment by Jarred-Sumner** [comment]
Test fails on Windows

I think we can mark the tests as TODO on windows and revisit later

**Comment by Jarred-Sumner** [comment]
@snoglobe 
- I skipped the test on Windows
- We didn't need to allocate when reading the environment variable, so I removed the allocation

After tests run again, I'll merge if it looks normal

**Pull request merged**
