### PR TITLE
Fix ffi type

### PR DESCRIPTION
**Pull request by codehz**
### What does this PR do?

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?

I used its type in https://github.com/codehz/bun_python/blob/%F0%9F%A5%9F/src/types.ts and verified it should works better than current types.

It's just two small changes:
1. Add Readonly so we can use `as const` to forced type narrow (when use with dedicated SYMBOLS table like that https://github.com/codehz/bun_python/blob/%F0%9F%A5%9F/src/symbols.ts#L277)
2. Split FFITypeToType to FFITypeToArgsType and FFITypeToReturnsType, it more precisely reflects the actual type than before.

### CODE REVIEW

**Comment by paperclover** [comment]
Looks good overall, but the type tests are failing. Can you fix those / Add more.

Also, I haven't played around with these typedefs myself, but does using `Readonly` like you are still allow usage without `as const`. Can you make sure the example on https://bun.sh/docs/api/ffi properly typechecks.

**Comment by codehz** [comment]
> but does using `Readonly` like you are still allow usage without `as const`.

Readonly doesn't prevent you to use mutable type, e.g. `const a: readonly number[] = []` pass the typecheck


> Can you fix those / Add more.

I will fix those soon

**Comment by codehz** [comment]
@paperdave now it should working, and several tests are added

**Comment by paperclover** [comment]
in ~30min im gonna manually git checkout and triple check

lgtm

**Review by paperclover — APPROVED** [review]

**Comment by paperclover** [comment]
Thank you

**Pull request merged**
