### PR TITLE
Follow more XDG conventions

### LINKED ISSUE #1678: Follow XDG Base Directory Specification
### What is the problem this feature would solve?

The `.bun/` directory unnecessarily pollute users' `$HOME` directory.
Related: #696, #965

### What is the feature you are proposing to solve the problem?

The [XDGBDS](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) defines where these files should be placed with environment variables to avoid polluting the `$HOME` directory.

From the XDGBDS:

> The XDG Base Directory Specification is based on the following concepts:
>
>   - There is a single base directory relative to which user-specific data files should be written. This directory is defined by the environment variable `$XDG_DATA_HOME`.
>
>   - There is a single base directory relative to which user-specific configuration files should be written. This directory is defined by the environment variable `$XDG_CONFIG_HOME`.
>
>   - There is a single base directory relative to which user-specific state data should be written. This directory is defined by the environment variable `$XDG_STATE_HOME`.
>
>   - There is a single base directory relative to which user-specific executable files may be written.
>
>   - There is a single base directory relative to which user-specific non-essential (cached) data should be written. This directory is defined by the environment variable `$XDG_CACHE_HOME`.
>
> User-specific executable files may be stored in `$HOME/.local/bin`.

### Implementing XDGBDS should work as follows:

_IF_ a corresponding XDG environment variable exists _THEN_ use it's location according to the spec.

_ELSE_ If the corresponding XDG_* env var is not defined, the program must fallback to the specified defaults:

env | fallback
-- | --
XDG_DATA_HOME | ~/.local/share
XDG_CONFIG_HOME | ~/.config
XDG_STATE_HOME | ~/.local/state
XDG_CACHE_HOME | ~/.cache

So the default/fallback directory layout mapping should be:

current | xdg compliant
-- | --
~/.bun/bin/bun | ~/.local/bin/bun
~/.bun/install/cache | ~/.cache/bun
~/.bun/install/global/node_modules | ~/.local/lib/node_modules
~/.bun/install/global/package.json | ~/.config/bun/package.json
~/.bun/install/global/bun.lockb | ~/.config/bun/bun.lockb

In addition, globally installed modules should go in `~/.local/lib/node_modules`, with binaries symlinked under `~/.local/bin` (which is what npm does).

### What alternatives have you considered?

We can also fallback to the `.bun` directory for backwards compatibility but as others have mentioned below this is not ideal and not part of the XDGBDS. 

The other alternative is to let all programs arbitrarily use the `$HOME` directory and create their own structure and organization for cache, data, config, etc. This is not optimal for any system with more than a few programs installed, which is why the XDGBDS exists to keep your system organized and easily navigable.

(Edited per [ju1ius](https://github.com/oven-sh/bun/issues/1678#issuecomment-1445187570), [ZerdoX-x](https://github.com/oven-sh/bun/issues/1678#issuecomment-1714398553))

### PR DESCRIPTION
**Pull request by booniepepper**
### What does this PR do?

I'm new to the codebase but I got hyped about the 1.0 release at the last hour

(If I'm following right) This should be the last little bit needed to close #1678 and prevent future breakage based on install locations

It also builds off of https://github.com/oven-sh/bun/pull/4438 from @lgarron

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

- [x] I ran `make zig` and it worked
- [x] I or my editor ran `zig fmt` on the changed files
- [ ] I included a test for the new code, or an existing test covers it
  - Not sure yet, I've only cloned the repo about an hour ago :)

### CODE REVIEW

**Comment by lgarron** [comment]
I think this would be a nice step, but nit on the title: this PR currently only covers the cache dir. There are also various other config and data paths in Bun that don't follow the XDG conventions.

In addition, some people believe would probably prefer for programs not to strictly adhere to the Linux-centered XDG conventions, but instead to use platform-specific defaults (e.g. `~/Library/Caches` on macOS) when the XDG vars aren't set. For example, see https://crates.io/crates/dirs/1.0.5 for a fairly thorough treatment of this in Rust.

**Comment by booniepepper** [comment]
Ah I didn't know there's more places. I've used that crate in some projects and it's def fantastic. I've referred to it when doing stuff outside Rust too

In that case... I guess I'd expect this to be switching on the OS in the Zig layer before getting to XDG_<ETC> and HOME handling. I don't know how many other layers (c++? js?) also need updates. I'm about to sign off for the night, but feel free to run with this or even cancel my PR. Some of my assumptions were off

**Comment by booniepepper** [comment]
@lgarron I updated the PR title; aside from that, do you think this looks like a good incremental step forward?

**Comment by ekhodx** [comment]
I would really like to see XDG specs implementation first. I hope it won't spread over months in order to include support for all platforms... Also I think most of MacOS and Windows users don't really care about where their apps store data, comparing to Linux and BSD. It should be implemented, but Linux specs go first imo.

@lgarron  are changes only include install script? if yes, it's probably very easy to finish in order to get merged.

I can't imagine new fresh tool like bun can end up getting to this table: https://wiki.archlinux.org/title/XDG_Base_Directory

**Comment by booniepepper** [comment]
> I can't imagine new fresh tool like bun can end up getting to this table: https://wiki.archlinux.org/title/XDG_Base_Directory

I added bun to the "Support > Partial" table, along with a workaround shell export that I think is sufficient to work around until the related XDG issue is resolved. It's a wiki, anyone can edit it. :) Feel free to update it later, I'm not an Arch user so I may forget about it

**Comment by lgarron** [comment]
> > I can't imagine new fresh tool like bun can end up getting to this table: https://wiki.archlinux.org/title/XDG_Base_Directory
> 
> I added bun to the "Support > Partial" table, along with a workaround shell export that I think is sufficient to work around until the related XDG issue is resolved. It's a wiki, anyone can edit it. :) Feel free to update it later, I'm not an Arch user so I may forget about it

I can't practically sign up for the wiki, as I don't seem to have access to a system that allows me to answer the anti-spam filter.

However,  I would suggest something like this:

> It is possible to set `export BUN_INSTALL="$XDG_DATA_HOME"/bun`. However, `bun` will prioritize using `$XDG_CONFIG_HOME`, `$XDG_CACHE_HOME`, and/or `$XDG_DATA_HOME` when these have been set.

**Comment by ekhodx** [comment]
> I added bun to the "Support > Partial" table

Thank you :)

> I'm not an Arch user so I may forget about it

Me neither but I have followed the issue and I would be very happy to remove this variable from my environment. I've left a comment above variable so that's not a problem :+1: 


> along with a workaround shell export that I think is sufficient to work around until the related XDG issue is resolved.

> However, I would suggest something like this:

Yes, thank you. I already read install script and shared this finding in issue thread: https://github.com/oven-sh/bun/issues/1678#issuecomment-1714380418

@booniepepper I also left some maybe useful info for you about XDG specs implementation: https://github.com/oven-sh/bun/issues/1678#issuecomment-1714398553

---

> I can't practically sign up for the wiki, as I don't seem to have access to a system that allows me to answer the anti-spam filter.

If you need it, you can just use minimal alpine docker image. This is the way you register on gentoo wiki also for example.

<details>
<summary>
And current captcha for arch wiki is
</summary>

`BIQC4LJNFYQCAIBAEAQCAIBAEAQCAIBAEAQCAICQMFRW2YLOEB3DMLRQFYZCALJANRUWEYLMOBWS`
</details>

**Comment by lgarron** [comment]
> And current captcha for arch wiki is
> `BIQC4LJNFYQCAIBAEAQCAIBAEAQCAIBAEAQCAICQMFRW2YLOEB3DMLRQFYZCALJANRUWEYLMOBWS`

Thanks, that worked! 😀 

> Yes, thank you. I already read install script and shared this finding in issue thread: [#1678 (comment)](https://github.com/oven-sh/bun/issues/1678#issuecomment-1714380418)
BIQC4LJNFYQCAIBAEAQCAIBAEAQCAIBAEAQCAICQMFRW2YLOEB3DMLRQFYZCALJANRUWEYLMOBWS

I was trying to make the point that setting `$BUN_INSTALL` can have counter-intuitive effects, in that it can *override* other settings like the cache dir:

https://github.com/oven-sh/bun/blob/e09129074883f7a73c0fa7b3af833c3d56e3b8da/src/install/install.zig#L3656C26-L3664

So right now it's not simple as "set `$BUN_INSTALL` and everything will get better". In fact, I myself specifically avoid setting that var, so that my `bun` cache is with all the other caches. (For caches in particular, you can actually set `$BUN_INSTALL_CACHE_DIR` as an even higher priority override. But this gets super hairy, whereas setting explicit values for the XDG dir vars results in the correct behaviour as long you don't *also* set `$BUN_INSTALL`.)

I think we're probably all agreed in this thread that the least confusing if all of `bun` fully followed the XDG dir conventions (potentially with platform-sensitive defaults) out of the box, though.

**Comment by Jarred-Sumner** [comment]
We aren't going to do this breaking change right now, but might revisit in the future

**Pull request closed without merging**
