### PR TITLE
zig: make throwInvalidArgumentTypeValue use JSError

### PR DESCRIPTION
**Pull request by nektro**
progress towards https://github.com/oven-sh/bun/issues/15141

### CODE REVIEW

**Comment by robobun** [comment]
@nektro, your commit 038ce1519d388aa855501003a60aa43a351bdb89 is building: [`#6526`](https://buildkite.com/bun/bun/builds/6526)

**Review by Jarred-Sumner — CHANGES_REQUESTED** [review]
We cannot merge this without tests that verify these bindings work.

**Review by cirospaciari — CHANGES_REQUESTED** [review]
Need update before merging
Screenshot 2024-11-26 at 15 00 31

**Review by cirospaciari — APPROVED** [review]

**Comment by nektro** [comment]
binding tests were added and fixed in https://github.com/oven-sh/bun/pull/15362, then pulled in during an earlier `main` merge

**Pull request merged**
