### PR TITLE
Fix react example manifest error

### PR DESCRIPTION
**Pull request by travis-wang-v1**
☀️ Comment out manifest since 'bun dev' could not load manifest correctly and caused the following errors:

1. GET http://localhost:3000/manifest.json 404 (Not Found)
2. Manifest: Line: 1, column: 1, Syntax error.

### CODE REVIEW

**Comment by FinnRG** [comment]
Could you create an issue, so that we can fix this?

**Comment by tom-sherman** [comment]
Created the issue in #494

**Comment by FinnRG** [comment]
Closed, because we really should fix the manifest error instead of just removing it from ```index.html```.

**Comment by lavahasif** [comment]
image

temporarly comment manifest line in index.html .in `bun dev`

**Pull request closed without merging**
