### PR TITLE
Fix TS experimental decorator crash

### LINKED ISSUE #11773: Crash in TS experimental decorators due to missing error check
Input:
```ts
function b(target: any) {}class a {@b(() => 1) abstract d;e = () => 1;}console.log("success")
```

```ts
Bun Canary v1.1.13-canary.1 (791ba794) macOS Silicon
Args: "bun" "b.ts"
Features: jsc bunfig
Builtins: "bun:main"
Elapsed: 9ms | User: 8ms | Sys: 8ms
RSS: 21.73MB | Peak: 21.73MB | Commit: 1.07GB | Faults: 50

panic(main thread): 1 | function b(target: any) {}class a {@b(() => 1) abstract d;e = () => 1;}console.log("success");
                                                                                                 ^
error: Expected scope (src.js_ast.Scope.Kind.function_args, 62) in /Users/jarred/Desktop/b.ts, found scope (src.js_ast.Scope.Kind.function_args, 38)
    at /Users/jarred/Desktop/b.ts:1:94

oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

fish: Job 1, 'bun b.ts' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

### PR DESCRIPTION
**Pull request by LeoWiniecki-PowerSystems**
### What does this PR do?
Throws an error if an abstract property is decorated to fix #11773

### How did you verify your code works?
ran on the example

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
Thank you for this, but I'm not sure it should be an error. It isn't an error in esbuild.

**Comment by forcefieldsovereign** [comment]
@Jarred-Sumner The bug was the TS decorator scopes not getting discarded for the abstract property.

**Comment by Jarred-Sumner** [comment]
I think this is relevant:
https://github.com/evanw/esbuild/blob/fc37c2fa9de2ad77476a6d4a8f1516196b90187e/internal/js_parser/js_parser.go#L2216-L2248

**Review by dylan-conway — APPROVED** [review]
Looks great!

**Comment by Jarred-Sumner** [comment]
This should not have been merged without tests

**Pull request merged**
