### PR TITLE
Docs: Add description on how to install specific version #843

### PR DESCRIPTION
**Pull request by surajpulloor**
Added code/instruction for installing specific bun version. The issue is #843

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
Thank you for this, but I don't really want to encourage people to download older versions. After bun is stable, I think it'd be interesting to move towards Chromium-like releases where virtually everyone is on latest. It needs a very good test suite before that though.

**Comment by surajpulloor** [comment]
ok cool

**Comment by onionhammer** [comment]
@Jarred-Sumner it would be useful to install older versions to better understand if a newer version of bun fixed a past version, or if the code now works because some other dependency changed.

I was going to add an issue to this repo outlining an issue I was having last week, but now i'm not sure what I was doing, but if I cant reproduce it anymore that doesnt necessarily mean the bug is fixed in Bun, it may just be that I'm doing something else in my code now

**Comment by pooledge** [comment]
> I was going to add an issue to this repo outlining an issue I was having last week, but now i'm not sure what I was doing, but if I cant reproduce it anymore that doesnt necessarily mean the bug is fixed in Bun, it may just be that I'm doing something else in my code now

Exactly. It may be still bleeding, and switching runtime version is essential for those of us, who use `bun` in production

**Comment by adamtomat** [comment]
As someone who maintains 30+ projects for clients, where node is only used to compile Fronted assets (and isn't installed on a production server), it doesn't make commercial sense for us as an agency to constantly keep bun up to date.

Currently we lock the version of node we use with nvm and even if we don't touch the project for 6-12 months, it's very likely that the node build process will still work. My concern with bun (without being able to pin versions) is that builds will randomly stop working. As we run this on CI too, it would mean we are unable to deploy until we resolve the issue (for x projects). And updating node/bun versions give us very little benefit.

So, while I can see the benefit from your side to encourage people to keep bun updated (especially if it's installed on a production server), commercially that just isn't viable for a lot of people who just use it for asset compilation etc. So having some consideration around that would be great from my perspective, because I do want to use bun.

So I'd be in favour of having documentation around pinning specific versions of bun - even if you add a caveat that you would still prefer people up keep up to date.

**Comment by duhaime** [comment]
Can this be reopened @Jarred-Sumner? For issues related to e.g. [OS incompatibilities](https://github.com/oven-sh/bun/issues/6035), it'd be nice to roll back to a specific version. 

People are already rolling back--documenting the process will just make life easier.

**Comment by ild0tt0re** [comment]
Would be nice a voltajs like system to change and pin a specific version of bun

**Comment by khromov** [comment]
@Jarred-Sumner Is it possible to reconsider this? It's unimaginable to run anything serious in production without being able to lock down all the dependencies. Otherwise every new deploy will be a spin of the roulette wheel on whether everything works in the latest version or not.

**Comment by khromov** [comment]
There are now docs for how to install a specific bun version, example:

```bash
curl -fsSL https://bun.sh/install | bash -s "bun-v1.0.30"
```

You can also use the `setup-bun` GitHub action to install the correct Bun version on GH Actions:

```yaml
  - name: Set up Bun
    uses: oven-sh/setup-bun@v1
    with:
      bun-version: 1.0.30
```

**Comment by nelsonsbrian** [comment]
what about a windows command? Im running into a bun issue that I want to narrow down the regression version and I cant get back to an older version...

**Pull request closed without merging**
