### PR TITLE
ensure `super()` is not merged with adjacent statements

### LINKED ISSUE #2744: Accessing readonly constructor parameters inside constructor while also extending a class gives error
### What version of Bun is running?

0.6.0

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

Create a file with the following code:

```ts
class Parent {}

class Child extends Parent {
  calc: number;

  constructor(readonly value: number) {
    super();
    this.calc = value / 2;
  }
}

const a = new Child(6);
console.log(a.calc);
```

And run it with `bun`

### What is the expected behavior?

Since this is valid TypeScript, the expected behavior is a console output of `3`

### What do you see instead?

I get the following output:

```console
 5 | class Parent {}
 6 | 
 7 | class Child extends Parent {
 8 |   calc: number;
 9 | 
10 |   constructor(readonly value: number) {
                           ^
ReferenceError: 'super()' must be called in derived constructor before accessing |this| or returning non-object.
      at new Child (./src/index.ts:10:23)
      at ./src/index.ts:16:10
```

### Additional information

When not extending another class, the code works fine. Also, when making the `value` property not `readonly`, the code works fine.

### PR DESCRIPTION
**Pull request by dylan-conway**
fixes #2744

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
What if you had `foo, super()`

**Comment by Jarred-Sumner** [comment]
I don’t know if we need to handle that case but this is an improvement over status quo so we should merge it

**Comment by dylan-conway** [comment]
> What if you had `foo, super()`

This will fail with the same error currently

**Comment by Jarred-Sumner** [comment]
Let’s merge once it finishes building

**Pull request merged**
