### PR TITLE
Fix update zls version in devcontainer

### PR DESCRIPTION
**Pull request by zhiyuang**
Fix `make devcontainer-build` failed. Related issue https://github.com/zigtools/zls/issues/960

update `zls` to latest commit

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
ah yeah going forward I suggest using the latest zls instead of the vendored one

**Comment by Jarred-Sumner** [comment]
we should just delete the locally installed version of the extension as well. its out of date

**Comment by zhiyuang** [comment]
> we should just delete the locally installed version of the extension as well. its out of date

ok, deleted

**Comment by Jarred-Sumner** [comment]
thank you

**Pull request merged**
