### PR TITLE
Update docs `bun` -> `bunx`

### PR DESCRIPTION
**Pull request by torn4dom4n**
### What does this PR do?

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

I think it's `bunx` to start bun server.

### CODE REVIEW

**Comment by malezjaa** [comment]
No, `bunx` is used to auto-install and run packages from npm. To run scripts you use `bun run <>`

**Comment by torn4dom4n** [comment]
@malezjaa it's my mistake

**Comment by malezjaa** [comment]
This is not necessary, because scripts in the package.json already use `next`.

**Comment by torn4dom4n** [comment]
@malezjaa Thanks for your info

**Pull request closed without merging**
