### PR TITLE
fix(child_process): handle stdout exceeds max buffer size

### PR DESCRIPTION
**Pull request by codymikol**
* resolve an issue where the calculated encodedStdoutLen would always be resolved to undefined due to never being initialized

* resolve an improper usage of 'apply' on StringPrototypeSlice where the arguments passed to apply are required to be passed as an array rather than varargs.

Fixes: #5319

### What does this PR do?

When stdout is too large, bun will crash due to both an uninitialized value "encodedStdoutLen" which always results in NaN and also an improper usage of `apply` on StringPrototypeSlice which would always result in an exception being thrown.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

The failing test case I provided in the attached issue now works as expected.

- [x] I ran `make js` and committed the transpiled changes
- [x] I or my editor ran Prettier on the changed files (or I ran `bun fmt`)
- [x] I included a test for the new code, or an existing test covers it

### CODE REVIEW

**Comment by codymikol** [comment]
Not sure about committing the transpiled changes, is that supposed to be the InternalModuleRegistryConstants.h ? I don't see any other transpiled files.

**Comment by dylan-conway** [comment]
> Not sure about committing the transpiled changes, is that supposed to be the InternalModuleRegistryConstants.h ? I don't see any other transpiled files.

Yes, for this change `InternalModuleRegistryConstants.h` would need to be committed

**Comment by codymikol** [comment]
✅

**Comment by dylan-conway** [comment]
could you also add a test for this in `child_process-node.test.js`?

**Comment by codymikol** [comment]
doing it now actually

**Comment by codymikol** [comment]
Kinda lost on these tests, bun test doesn't seem to be evaluating my changes in child_process, is there a more correct way to run these tests?

**Comment by codymikol** [comment]
scratch that, I'm a dummy

**Comment by codymikol** [comment]
I feel pretty good about the tests now, this should be ready to review

**Comment by codymikol** [comment]
rebased and formatted

**Comment by Electroid** [comment]
Oops, I accidentally broke this while testing, will fixup.

**Comment by codymikol** [comment]
Are you still interested in this fix?

**Comment by Electroid** [comment]
If you could force push up your changes that would be great, we can adapt it. My bad for messing up the diff.

**Comment by codymikol** [comment]
:heavy_check_mark:

**Comment by codymikol** [comment]
its cool, don't sweat it

**Pull request closed without merging**
