### PR TITLE
fix(run): interpret extensionless files as typescript

### LINKED ISSUE #5173: TypeScript does not work in shebang scripts
```ts
#!/usr/bin/env bun
const text = "bun" as string;
console.log(text);
```
Upon executing the script, this happens.
```bash
error: Expected ";" but found "as"
const text = "bun" as string;
```
Removing the typescript part fixes the issue.

_Originally reported on Discord: [`Bun shebang scripts don't transpile typescript.`](https://discord.com/channels/876711213126520882/1143445141621841930/1143445141621841930)_

### PR DESCRIPTION
**Pull request by paperclover**
### What does this PR do?

also fixes `require('yargs/yargs')`. im surprised we did not have an open issue about this.

Fixes #5173
Furthers #4207 

i wrote automated tests

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
does not compile

**Comment by liz3** [comment]
Another good testcase for this might be googles [zx](https://github.com/google/zx).
Since it is designed as a shell scripting system using the node ecosystem.

**Comment by paperclover** [comment]
the build failure was a ci issue.

**Comment by paperclover** [comment]
fixed linux test failure

**Comment by Jarred-Sumner** [comment]
yargs-cjs test is failing

**Comment by Jarred-Sumner** [comment]
LGTM.

**Pull request merged**
