### PR TITLE
[bench] hashing: coerce deno pointers to use numbers

### PR DESCRIPTION
**Pull request by littledivy**
also, can you update Deno to 1.23.4? thanks

### CODE REVIEW

**Comment by sno2** [comment]
I'm a little confused about this.  Wouldn't most users just use the built-in `pointer` type anyways at which point the casting to a `Number` as a performance trick in a benchmark be obsolete in practically all implementations?

**Comment by littledivy** [comment]
pointer is just a bigint. It's totally practical for performance-hungry code to cast to number and lose some bits, this is Bun's default.

**Comment by Jarred-Sumner** [comment]
Happy to update to Deno 1.23.4. 

Not going to do this coercion, as it feels like gaming. Consider making Deno's implementation faster, so that users of Deno benefit.

**Comment by littledivy** [comment]
I just wanted to make the benchmark look fair because it does not take into account how pointers are represented in both runtimes. The code right now is not identical. It's sad that you think this is gaming.

**Comment by evanwashere** [comment]
this moves pointer out of benchmark which in some way counts as unrealistic scenario

both deno and bun get pointer inside benchmark to match what users would actually do

another way to represent this is
```js
function hash(buffer) {
  ....ffi logic....
}
```

**Comment by KnorpelSenf** [comment]
@Jarred-Sumner are there more unfair benchmarks?

**Pull request closed without merging**
