### PR TITLE
[bun install] Add `-E` as alias of `--exact`

### PR DESCRIPTION
**Pull request by jonahsnider**
### What does this PR do?

`bun install` and `bun add` both support the `--exact` flag for pinning a dependency's version.
This adds a shorter `-E` flag as an alias, something that [npm](https://docs.npmjs.com/cli/v10/commands/npm-install#save-exact:~:text=additional%2C%20optional%20flags%3A-,%2DE%2C%20%2D%2Dsave%2Dexact,-%3A%20Saved%20dependencies%20will), [Yarn](https://yarnpkg.com/cli/add#options-E%2C-exact), and [pnpm](https://pnpm.io/cli/add#--save-exact--e) also support.

- [ ] Documentation or TypeScript types
  - There are a few examples of how to use `--exact` where it may be helpful to have examples for `-E` as well
  - I think it's fine to leave them as-is though
- [x] Code changes

### How did you verify your code works?

I've tested locally and confirmed that the flag works as expected:

screenshot of `bun install zod -E` working locally

There are existing tests for `--exact`. If it'd be useful, those could be duplicated to do the same assertions but with `-E` instead of `--exact. The only thing that'd test would be the CLI arg parsing though, not sure if that's useful.

- [x] I or my editor ran `zig fmt` on the changed files
- [x] I included a test for the new code, or an existing test covers it

### CODE REVIEW

**Comment by Electroid** [comment]
Thanks for adding this! Mind also adding a test, you can copy-paste from this:
https://github.com/oven-sh/bun/blob/92e95c86dd100f167fb4cf8da1db202b5211d2c1/test/cli/install/bun-add.test.ts#L304

**Comment by jonahsnider** [comment]
Added a test for `-E`

**Comment by BrennanColberg** [comment]
strongly support this, my default `[manager] install -DE` works on npm/pnpm/yarn but not here

**Comment by v3nntrnx** [comment]
LGTM

**Review by Electroid — APPROVED** [review]

**Pull request merged**
