### PR TITLE
Display the version installed after installing

### LINKED ISSUE #3720: Add bun version into CLI output of the install script
### What is the problem this feature would solve?

image

### What is the feature you are proposing to solve the problem?

to know which bun version was installed

### What alternatives have you considered?

you can run `bun -v` to check, but this would be a nice inclusion

### PR DESCRIPTION
**Pull request by MohammedWaheeb**
This was requested by a user on twitter 

Closes #3720

### CODE REVIEW

**Comment by Electroid** [comment]
Instead of making a request to the Github API, it can just output the result of `bun -v`

**Comment by MohammedWaheeb** [comment]
@Electroid done

**Comment by paperclover** [comment]
Closes #3720

(i know typing this in the main comment will make it close but idk if i type it in a comment here)

**Comment by MohammedWaheeb** [comment]
@paperdave is there anything i need to do so it can be merged

**Comment by birkskyum** [comment]
can we make a way to print the commit hash a version is build from?

When I use `bun -v` i just see the generic:

```
➜ bun -v
0.7.4
```


**An example of a more informative cli is **rustc**:**

``` zig
➜ rustc -V
rustc 1.70.0 (90c541806 2023-05-31) (built from a source tarball)
```

**Comment by paperclover** [comment]
> can we make a way to print the commit hash a version is build from?
> 
> When I use `bun -v` i just see the generic:
> 
> ```
> ➜ bun -v
> 0.7.4
> ```
> 
> **An example of a more informative cli is rustc:**
> 
> ```zig
> ➜ rustc -V
> rustc 1.70.0 (90c541806 2023-05-31) (built from a source tarball)
> ```

#4027 added `bun --revision` which prints a string like

```
0.7.4-debug+d6cf039ccd0e3fd36f57564c816e68fef1403189
```

(we cannot change -v because bun upgrade relies on it and would break older bun upgrades)

**Comment by MohammedWaheeb** [comment]
@paperdave should i add it next to or under the version

**Pull request closed without merging**
