### PR TITLE
[install] fix connection error detection

### PR DESCRIPTION
**Pull request by alexlamsl**

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
I'm not sure we can actually do this because we might have to free the response body. Instead, `.isSuccess()` should be used

**Comment by alexlamsl** [comment]
Response body seems to reside within `AsyncHTTP.response_buffer` rather than `.response`:

https://github.com/oven-sh/bun/blob/42f6b35a5be8bc0b48f7643618a8458c146e8272/src/http_client_async.zig#L1164-L1169

and at least in the case of `install.zig` is owned by the caller:
https://github.com/oven-sh/bun/blob/42f6b35a5be8bc0b48f7643618a8458c146e8272/src/install/install.zig#L324-L330

**Comment by Jarred-Sumner** [comment]
you're right

**Comment by Jarred-Sumner** [comment]
thank you

**Pull request merged**
