### PR TITLE
Use singular nouns when appropriate on install messages

### PR DESCRIPTION
**Pull request by jakeboone02**
Updates the messages from `bun install` to use the singular form of nouns when referring to only one of something. Otherwise, the plural form is used as it currently does in all cases.

E.g., instead of `"1 packages installed"` it will now say `"1 package installed"` or `"2 packages installed"`.

(I don't have an environment to test this, so I'm just hoping it works... This is also my first time to work with Zig.)

### CODE REVIEW

**Comment by paperclover** [comment]
https://github.com/oven-sh/bun/blob/5b9ed9547c296e3f5cad8c15581cd607d58840ba/test/cli/install/bun-link.test.ts#L344

missing one more packages -> package

i ran it locally and the build works and tests pass on my machine, besides that one and also something else that was already failing.

**Comment by jakeboone02** [comment]
> https://github.com/oven-sh/bun/blob/5b9ed9547c296e3f5cad8c15581cd607d58840ba/test/cli/install/bun-link.test.ts#L344

@paperdave - Fixed with f52b4923be871140ab540df57c17c61cb248839a:

https://github.com/oven-sh/bun/blob/f52b4923be871140ab540df57c17c61cb248839a/test/cli/install/bun-link.test.ts#L344

**Review by paperclover — APPROVED** [review]
love it

**Comment by jakeboone02** [comment]
@paperdave I merged from `main` so this is probably good to go (again).

**Comment by paperclover** [comment]
sorry, i missed these notifications. lets get this merged soon.

having ci run tests and otherwise will merge

**Comment by jakeboone02** [comment]
> sorry, i missed these notifications. lets get this merged soon.
> 
> having ci run tests and otherwise will merge

@paperdave no problem. Looks like 9a65f7beec271c3ff70d72d53e023487b7d41370 was failing tests and prettier. Latest merge 31926239ccf31217ecf1a5700447678a60845ce9 fixes prettier but not tests. Working on that now.

**Comment by jakeboone02** [comment]
@paperdave ok should be good to go with 302fef04d8b73397d4e8e2fa7062050f6060672c

**Comment by paperclover** [comment]
image
seems some new tests since the merge were failing?

**Comment by jakeboone02** [comment]
Alright, let's try again

**Pull request merged**
