### PR TITLE
chore(docs): improve readme.md markdown structure

### PR DESCRIPTION
**Pull request by okineadev**
### What does this PR do?

Improved the Markdown structure in `README.md`, replaced HTML tags with native Markdown, which greatly improved the readability of Markdown

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
Really appreciate your enthusiasm, though using regular HTML there was intentional to be more precise than what the markdown renderer does

**Comment by okineadev** [comment]
You will regret it...

**Comment by okineadev** [comment]
> HTML there was intentional to be more precise than what the markdown renderer does

How will you prove that it is more accurate and better?

Can you show some articles or other materials that confirm this?

After my changes, at least something shifted by one pixel ??


I don't think this is the right decision

**Comment by sequencerr** [comment]
Don't make such a fuss over a markdown change and adjust your tone. This only makes your pr less likely to be merged

**Pull request closed without merging**
