### PR TITLE
fix: Bun.serve logging error when fetch returns rejected promise

### PR DESCRIPTION
**Pull request by LukasKastern**
### What does this PR do?

Fixes: #1435 
Promises that were rejected before reaching the `RequestContext` `onResponse` method would print their error to the output.  
This change "handles" the returned promise to avoid logging the error message. 

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

I wrote automated tests

### CODE REVIEW

**Comment by TiBianMod** [comment]
is this really the fix for https://github.com/oven-sh/bun/issues/1435 ??

I'm waiting 1y for this, hehe

**Comment by Jarred-Sumner** [comment]
Thank you

**Comment by TiBianMod** [comment]
Thank you @LukasKastern 

can we add also support for `async error` ?


```js
Bun.serve({
    port: 3000,
    fetch: async () => {
        throw new Error("A");

        return new Response("A");
    },
    error: async () => {
        // some async operation
        await Bun.sleep(100);

        return new Response("Handled");
    },
});

```

**Comment by LukasKastern** [comment]
> Thank you @LukasKastern

No worries.

> can we add also support for `async error` ?
> 
> ```js
> Bun.serve({
>     port: 3000,
>     fetch: async () => {
>         throw new Error("A");
> 
>         return new Response("A");
>     },
>     error: async () => {
>         // some async operation
>         await Bun.sleep(100);
> 
>         return new Response("Handled");
>     },
> });
> ```

I can look into that one. Could you create an issue that I can refer to?

**Comment by TiBianMod** [comment]
yes sure 😄 

https://github.com/oven-sh/bun/issues/8217

**Pull request merged**
