### PR TITLE
install: fix issues with patching hoisted dependencies in workspaces

### LINKED ISSUE #12103: `bun patch` not working in monorepo
### What version of Bun is running?

1.1.16+bf7b327f6

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

Our monorepo contains plenty of apps / packages all defined in the root `package.json` workspaces array of our monorepo. After upgrading to bun 1.1.16 the following screen shot shows off the issue I am running into. 

CleanShot 2024-06-23 at 21 35 07@2x

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zackradisic**
### What does this PR do?

Fixes #12103 

Specifically the issue was `bun patch` not properly handling hoisted dependencies in workspaces

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
windows test failures

**Comment by Scalahansolo** [comment]
Was curious to know if this might be making it into a release soon? The team over here at Motion is pretty anxious to try and swap yarn out for bun at the install layer and we think this is the last blocker.

**Comment by flokol120** [comment]
> Was curious to know if this might be making it into a release soon? The team over here at Motion is pretty anxious to try and swap yarn out for bun at the install layer and we think this is the last blocker.

Exactly the same situation over here. 😅

**Comment by Thiagolino8** [comment]
> Was curious to know if this might be making it into a release soon? The team over here at Motion is pretty anxious to try and swap yarn out for bun at the install layer and we think this is the last blocker.

Same here

**Comment by dylan-conway** [comment]
@Scalahansolo @flokol120 @Thiagolino8 We plan to have this included in the next release (1.1.18). There isn't a date for the release yet, but I would expect first half of next week

**Review by dylan-conway — APPROVED** [review]

**Pull request merged**
