### PR TITLE
Add `bun docs`

### PR DESCRIPTION
**Pull request by rmorey**
Adds `bun docs` which opens https://bun.sh/docs. 

Copied entirely from the implementation of `bun discord`

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
The part of this I'm not sure about is 

Will this break someone's script that runs `bun docs`? Now they'll have to do `bun run docs`

**Comment by rmorey** [comment]
> Will this break someone's script that runs bun docs? Now they'll have to do bun run docs

@Jarred-Sumner That's a really good point. And `docs` in particular is probably a likely script name. Maybe check for `docs` in scripts, if not there launch bun docs? This is kind of a general problem for the auto command

**Comment by xhyrom** [comment]
From my point of view, we shouldn't overwhelm the CLI with commands that just open the page, it's pointless. When you download bun, you see on the web that it has documentation and stuff. I would consider maybe deleting the `bun discord` for the same reason.
- Nobody probably uses the `discord` script, but it's unnecessary

It would be interesting to do some "docs in terminal" that wouldn't need to open the web but that could already be implemented as another package (like https://github.com/vaporoxx/djsdocs for example).

**Comment by rmorey** [comment]
> From my point of view, we shouldn't overwhelm the CLI with commands that just open the page, it's pointless. 

I agree, closing this PR

**Comment by v3nntrnx** [comment]
> From my point of view, we shouldn't overwhelm the CLI with commands that just open the page, it's pointless. When you download bun, you see on the web that it has documentation and stuff. I would consider maybe deleting the `bun discord` for the same reason.
> 
>     * Nobody probably uses the `discord` script, but it's unnecessary
> 

I agree with that one, we probably should delete the discord script

**Pull request closed without merging**
