### PR TITLE
fix(process): enable SIGKILL and SIGSTOP mappings

### PR DESCRIPTION
**Pull request by antongolub**
### What does this PR do?

This PR enables _fast_ child process killing (execa, zx scripts) via `SIGKILL`

```bash
p.kill("SIGKILL")
...
RangeError: Unknown signal name
      at ~/zx-extra/node_modules/zx/build/core.js:251:16
      at processTicksAndRejections (:61:7
```

### How did you verify your code works?

I've tweaked a test:
```bash
bun run build
bun-debug test ./test/js/node/process/process.test.js
```

### CODE REVIEW

**Comment by antongolub** [comment]
@dylan-conway,

As I can see, you've introduced this behaviour. Why the mapping was disabled?

**Comment by Jarred-Sumner** [comment]
I think I misread `SIGKILL` as `SIGILL` (when we discussed IRL)

**Review by Jarred-Sumner — APPROVED** [review]
LGTM

**Comment by Electroid** [comment]
SIGSTOP is also commented out.

**Comment by antongolub** [comment]
@Jarred-Sumner

Should we enable `SIGSTOP` too?

**Review by dylan-conway — CHANGES_REQUESTED** [review]
`signalNameToNumberMap` is also used for `process.on(<signal name>, ...);` and it's not possible to set handlers on SIGKILL and SIGSTOP. We can uncomment both of them but will need to add something like this in `onDidChangeListeners` on line 804 and 752:
```cpp
if (auto signalNumber = signalNameToNumberMap->get(eventName.string())) {
            if (signalNumber != SIGKILL && signalNumber != SIGSTOP) {
...
```

**Review by dylan-conway — APPROVED** [review]
LGTM. will merge after ci runs

**Comment by dylan-conway** [comment]
Thank you

**Pull request merged**
