### PR TITLE
Implement util.MIMEType and util.MIMEParams

### PR DESCRIPTION
**Pull request by gaurishhs**
### What does this PR do?

This implements util.MIMEType and util.MIMEParams

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

- [x] I ran `make js` and committed the transpiled changes
- [x] I or my editor ran Prettier on the changed files (or I ran `bun fmt`)
- [ ] I included a test for the new code, or an existing test covers it

- [x] I added TypeScript types for the new methods, getters, or setters

### CODE REVIEW

**Review by Xachiey — COMMENTED** [review]
Maybe you shouldn't change the style of the codebase. 
Just focus on modifying the functionality.
:D

**Comment by Jarred-Sumner** [comment]
Thank you for this 

util needs to be implemented more in native code. The amount of JavaScript in Bun is growing too much, which costs start time and execution time. Bun already has an internal implementation of something very much like util.MIMEType. It's missing util.MIMEParams. If you want to attempt a Zig implementation of this, have a look in src/http/mime_type.zig. There are also WebKit implementaitons of Content-Type header parsing which might be helpful here.

**Comment by gaurishhs** [comment]
@Jarred-Sumner i understand that, do you have any examples of any built in modules which are completely in zig rn? 

EDIT: i saw the dns implementation, so i should probably implement it in zig in (src/bun.js) and then declare a property util on the Bun global ( `Bun.util`) and then call each zig function in js? there should be something to directly import zig in js files something similar to what hyperimport did but that was a bun plugin..

**Comment by gaurishhs** [comment]
> Maybe you shouldn't change the style of the codebase. Just focus on modifying the functionality. :D

i didn't do the formatting changes they are probably due to `bun fmt` which i ran as said when opening the PR

**Pull request closed without merging**
