### PR TITLE
add `isntall` alias for install command

### PR DESCRIPTION
**Pull request by sk337**
### What does this PR do?

This adds `isntall` alias for install command

### CODE REVIEW

**Comment by paperdave** [comment]
i guess this is because of?

image

it might be better to just push people towards shorter aliases like `bun i` instead of adding typo aliases

**Comment by sk337** [comment]
yes and i am tired of rerunning the command whenever i make that typo and dont notice it.

**Comment by Anush008** [comment]
There are also these possible values.

https://github.com/npm/cli/blob/latest/lib%2Futils%2Fcmd-list.js#L120-L128

**Comment by jdalton** [comment]
> Referen

@sk337 Can you align with the list `npm` has ☝️

**Comment by paperdave** [comment]
the more i think about this the more i dont want this. we should add to the script not found message a "note" message "did you mean 'bun install'"

this would make it so someone with a script named istall would run, instead of not running (maybe someome out there has some tallness detector script)

we could then open this up to ALOT of more typos for all commands.

**Comment by sk337** [comment]
> > There are also these possible values.
> > https://github.com/npm/cli/blob/latest/lib%2Futils%2Fcmd-list.js#L120-L128
> 
> @sk337 Can you align with the list `npm` has ☝️

ok

**Comment by paperdave** [comment]
this is far too many. bun does not need to match the npm cli interface. someone with a script named `in` will no longer work. see previous comment

**Comment by Jarred-Sumner** [comment]
I don’t think we should do this. The terminal can provide this feature for you

**Pull request closed without merging**
