### PR TITLE
fix(examples/hono): refine Hono example

### PR DESCRIPTION
**Pull request by yusukebe**
* Bump up Hono version number
* Simplify the script
* Add tests

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi!

Resolved conflict.

**Comment by LoiLock** [comment]
Is the version bump to 2.0.2 really necessary? ^2.0.0 matches 2.0.2 as well, so it will install this as well

**Comment by yusukebe** [comment]
@LoiLock 

Sorry, it's not necessary. fixed it.

**Comment by FinnRG** [comment]
The ``wiptest`` function is still a WIP, so I wouldn't include it in a template.

**Comment by yusukebe** [comment]
Hi @FinnRG 

I've removed the test. If the `wiptest` become not a WIP, I'll use it.
Thank you!

**Review by FinnRG — APPROVED** [review]

**Pull request merged**
