### PR TITLE
Update Svelte Kit Docs

### PR DESCRIPTION
**Pull request by e253**
I added some guidance about how to build for production. Still WIP since I would like to add a more complete deployment guide.

### What does this PR do?

- [X] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### CODE REVIEW

**Comment by happysalada** [comment]
hey just a question as an outsider, bun's aim to replace vite right ?
Right now vite is still needed but in the future if there is better integration, we should be able to remove it?
(I couldn't find the answer to this anywhere, so I'm asking here. No worries if you are busy though).

**Comment by e253** [comment]
Not sure either. I think that bun *could* replace vite in sveltekit. At the moment, you can use bun to install deps and run the project in production.

**Comment by colinhacks** [comment]
Thanks!

**Comment by elvisisvan** [comment]
> hey just a question as an outsider, bun's aim to replace vite right ? Right now vite is still needed but in the future if there is better integration, we should be able to remove it? (I couldn't find the answer to this anywhere, so I'm asking here. No worries if you are busy though).

what? i thought bun is to replace deno?

**Pull request merged**
