### PR TITLE
fix: don't inline process.env calls in runtime 

### PR DESCRIPTION
**Pull request by liz3**
### What does this PR do?
This caused issues with reassigning or deleting env vars as the inlining into a static
value meant that the changes would not be reflected at the runtime, while maybe it would be
somehow possible to do static analyisis whether a value is changed that is massively out of scope.
This disables the inlining of environment variables at transpile time.

Fixes: https://github.com/oven-sh/bun/issues/6762
Fixes: https://github.com/oven-sh/bun/issues/4383

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

- [x] I included a test for the new code, or an existing test covers it

### CODE REVIEW

**Review by Jarred-Sumner — CHANGES_REQUESTED** [review]
This breaks loading .env files for:
- The runtime in general?
- `bun run <package-json-script>`
- `bun install <lifecycle-package-json-script>`

**Comment by liz3** [comment]
@Jarred-Sumner apologize for that i assumed the behaviour was only for inlining, i refactored it to be a seperate setting

**Comment by michaelhays** [comment]
Hey there, anything left to do here? I'm happy to test on my machine if there's a way I can do that

**Comment by michaelhays** [comment]
Sorry to push, but is there anything I can do to help this get merged?

My project has local scripts which prompt the environment, and then load our environment variables into `process.env` based on that response, so having this work in Bun would improve our workflow a ton!

```ts
const environment = await promptEnvironment()

process.env = {
  ...process.env,
  ...environmentGetEnvVars(environment),
}

const user = await prisma.user.findUniqueOrThrow({ where: ... })
```

**Comment by liz3** [comment]
> Sorry to push, but is there anything I can do to help this get merged?
> 
> My project has local scripts which prompt the environment, and then load our environment variables into `process.env` based on that response, so having this work in Bun would improve our workflow a ton!
> 
> ```ts
> const environment = await promptEnvironment()
> 
> process.env = {
>   ...process.env,
>   ...environmentGetEnvVars(environment),
> }
> 
> const user = await prisma.user.findUniqueOrThrow({ where: ... })
> ```

It seams for regular env variables(not NODE_ENV) this has been resolved, i suspect by https://github.com/oven-sh/bun/pull/7365, at least i can't reproduce the issue anymore.
The reason this didn't get merged is that there is a issue with numerical var keys i.e `123`or `345623` with the underlying engine, you should'nt notice that though with release builds since it only crashes in debug builds.

Should you be in a case where this still happens(upgrade bun maybe if possible), you can work around this by tricking the transpiler:
```js
const getEnv = (k) => process.env[k];

console.log(getEnv("FOO"))
 process.env["FOO"] = "NEW-VALUE";
console.log(getEnv("FOO"))
```
Liz

**Comment by michaelhays** [comment]
Right you are! Upgrading to Bun 1.0.15 fixed this for me :)

Thanks so much @liz3!

**Pull request closed without merging**
