### PR TITLE
Substitute js/ for test/js/ (404)

### PR DESCRIPTION
**Pull request by guest271314**
Substitute js/ for test/js/ (404)

### CODE REVIEW

**Comment by paperclover** [comment]
the pr title is in reverse but this change is correct. related: i have a suspicion this entire file is out of date

**Comment by guest271314** [comment]
We are substituting js/ for test/js. The subject matter (person, place, thing, word) comes first, the replacement last.

**Comment by Electroid** [comment]
This isn't correct.

**Comment by guest271314** [comment]
> This isn't correct.

What do you mean? The link here

```
[`test/js/`](test/js/)
```

is 404 because the document is already in test yet the link is to test so the URL winds up being `test/test/js`.

**Comment by guest271314** [comment]
Screenshot_2024-02-09_18-04-42

**Comment by guest271314** [comment]
Screenshot_2024-02-09_18-04-42

**Comment by guest271314** [comment]
@Electroid What is incorrect? See the 404 error I'm referring to in the attached screenshot above.

**Comment by Electroid** [comment]
I misread it

**Pull request merged**
