### PR TITLE
`bun:sql` is a fast builtin SQL client, starting with PostgreSQL support

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

This adds a fast builtin postgres client to bun, under a new `bun:sql` module.

```zig

❯ bun bun-sql.ts
cpu: Apple M1 Max
runtime: bun 1.0.6 (arm64-darwin)

benchmark                                         time (avg)             (min … max)       p75       p99      p995
------------------------------------------------------------------------------------ -----------------------------
SELECT "Id" FROM "OrderDetail" LIMIT 10 x 10  137.02 µs/iter (101.38 µs … 736.17 µs) 137.58 µs 396.83 µs 566.54 µs
SELECT * FROM "OrderDetail" LIMIT 10 x 10     161.61 µs/iter    (128.04 µs … 1.5 ms) 162.46 µs 255.75 µs 598.13 µs

❯ node postgresjs-sql.mjs
cpu: Apple M1 Max
runtime: node v20.8.0 (arm64-darwin)

benchmark                                                         time (avg)             (min … max)       p75       p99      p995
---------------------------------------------------------------------------------------------------- -----------------------------
SELECT "Id" FROM "OrderDetail" LIMIT 10 x 10 - "postgres.js"  235.55 µs/iter      (148.17 µs … 1 ms) 239.67 µs 585.38 µs 706.42 µs
SELECT "Id" FROM "OrderDetail" LIMIT 10 x 10 - "pg"           427.25 µs/iter   (349.88 µs … 3.33 ms) 440.92 µs 632.79 µs   1.32 ms
SELECT * FROM "OrderDetail" LIMIT 10 x 10 - "postgres.js"     261.75 µs/iter     (205.5 µs … 1.7 ms) 270.71 µs 338.46 µs 480.88 µs
SELECT * FROM "OrderDetail" LIMIT 10 x 10 - "pg"              511.38 µs/iter   (435.42 µs … 2.69 ms) 510.75 µs   1.02 ms   1.77 ms
```

<details>

<summary>bun-sql.ts</summary>

```ts
import { sql, Sql } from "bun:sql";
import { bench, run } from "mitata";
process.env.DATABASE_URL = "postgres://jarred@localhost:5432/northwind";

bench(`SELECT "Id" FROM "OrderDetail" LIMIT 10 x 10`, async () => {
  const promises = new Array(10);
  for (let i = 0; i < 10; i++) {
    promises[i] = sql`SELECT "Id" FROM "OrderDetail" LIMIT 10`;
  }
  const results = await Promise.all(promises);
});

bench(`SELECT * FROM "OrderDetail" LIMIT 10 x 10`, async () => {
  const promises = new Array(10);
  for (let i = 0; i < 10; i++) {
    promises[i] = sql`SELECT * FROM "OrderDetail" LIMIT 10`;
  }
  const results = await Promise.all(promises);
});

await run();
```

</details>

<details>

<summary>postgresjs-sql.mjs</summary>

```js
import SQL from "postgres";
import { bench, run } from "mitata";
import pg from "pg";
const client = new pg.Client({
  database: "northwind",
  user: "jarred",
});
await client.connect();
const sql = SQL({
  // This is the default
  hostname: "localhost",
  port: 5432,
  username: "jarred",
  password: "",
  database: "northwind",
});

bench(
  `SELECT "Id" FROM "OrderDetail" LIMIT 10 x 10 - "postgres.js"`,
  async () => {
    const promises = new Array(10);

    for (let i = 0; i < 10; i++) {
      promises[i] = sql`SELECT "Id" FROM "OrderDetail" LIMIT 10`;
    }
    const results = await Promise.all(promises);
  }
);

const query = {
  // give the query a unique name
  name: "select-order-details",
  text: `SELECT "Id" FROM "OrderDetail" LIMIT 10`,
  values: [],
};
bench(`SELECT "Id" FROM "OrderDetail" LIMIT 10 x 10 - "pg"`, async () => {
  const promises = new Array(10);

  for (let i = 0; i < 10; i++) {
    promises[i] = client.query(query);
  }
  const results = await Promise.all(promises);
});

bench(`SELECT * FROM "OrderDetail" LIMIT 10 x 10 - "postgres.js"`, async () => {
  const promises = new Array(10);

  for (let i = 0; i < 10; i++) {
    promises[i] = sql`SELECT * FROM "OrderDetail" LIMIT 10`;
  }
  const results = await Promise.all(promises);
});

const query2 = {
  // give the query a unique name
  name: "select-order-star-details",
  text: `SELECT * FROM "OrderDetail" LIMIT 10`,
  values: [],
};
bench(`SELECT * FROM "OrderDetail" LIMIT 10 x 10 - "pg"`, async () => {
  const promises = new Array(10);

  for (let i = 0; i < 10; i++) {
    promises[i] = client.query(query2);
  }
  const results = await Promise.all(promises);
});

await run();

process.exit(0);
```
</details>

TODO before shipping:
- [ ] Fix GC issue with lots of allocations. Most likely missing a GCDeferralContext.
- [ ] Fix error handling 
- [ ] Handle integers and dates and more data types
- [ ] Password authentication
- [ ] Unix socket support
- [ ] TLS
- [ ] Docs. Mention we have a more limited feature set and to consider using the `postgres` package if we are missing a feature they need

Ideally, we would copy someone else's test suite. 

Some more configuration we should add:
- timeouts and retries

### How did you verify your code works?

This needs test coverage, particularly:
- the various data types
- errors
- Multiple simultaneous connections
- Stress tests

### CODE REVIEW

**Comment by porsager** [comment]
Very cool @Jarred-Sumner 😍 Congrats on getting that in!

I've actually found Postgres.js to run faster on Bun than Node.js, so just out of curiosity it'd be interesting to see that included in your benchmark.

Are these benchmarks with a single connection btw?

**Comment by GingerAdonis** [comment]
Why is the module named 'bun:sql'? The X poll you did earlier suggested you're considering a MySQL client as well. Wouldn't the module names conflict?

**Comment by e0** [comment]
> Why is the module named 'bun:sql'? The X poll you did earlier suggested you're considering a MySQL client as well. Wouldn't the module names conflict?

Saw Jarred mention this on Twitter:

> This is intended to later support multiple SQL adapters with the same interface, but we went with Postgres first for this api

Link: https://twitter.com/jarredsumner/status/1713815022659567655

**Comment by aquapi** [comment]
Will this be typesafe?

**Comment by uNetworkingAB** [comment]
I was counting on postgres.js being yet another premature superlative usage and looks to have been right. Interesting! Having one common interface for all SQL dbs, optimized as a built-in is the obvious way to go. These commonly used core features should not be implemented in soggy script

**Comment by jadbox** [comment]
Just a note here to support `connect()` for edge socket poolers. Postgres.js added this support in their recent update.
https://developers.cloudflare.com/workers/runtime-apis/tcp-sockets/

**Comment by PodaruDragos** [comment]
What is the status on this ? is this still being considered ?

**Comment by henryzhang03** [comment]
just bumping this issue, having problems with Postgres.js on Bun so really hope this can work out.

**Comment by Jarred-Sumner** [comment]
Closing in favor of https://github.com/oven-sh/bun/pull/11920

**Pull request closed without merging**
