### PR TITLE
Fix occasional test failure in setTimeout.test.js

### PR DESCRIPTION
**Pull request by argosphil**
### What does this PR do?

This modifies a timer test to call performance.now() before the critical section rather than from within it. It also fixes an incorrect expected value in the test.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

The test now succeeds reliably, even running it in a tight loop.

### CODE REVIEW

**Comment by argosphil** [comment]
#8834 is a similar issue which discusses changing Bun behavior to match the expectation of this test (and also get closer to documented behavior). I think we should apply both changes.

**Comment by argosphil** [comment]
This is superseded by #8859 , which fixes Bun.sleep() so the test matches both @cirospaciari 's expectations and the documenation.

**Comment by gvilums** [comment]
> This is superseded by #8859 , which fixes Bun.sleep() so the test matches both @cirospaciari 's expectations and the documenation.

Does this mean that this PR is good to close?

**Comment by argosphil** [comment]
Closing, we'll probably fix #8834 another way.

**Comment by jdalton** [comment]
Fixed by https://github.com/oven-sh/bun/pull/8950

**Pull request closed without merging**
