### PR TITLE
Revert "fix overriding `sshCommand` and `askpass` from gitconfig"

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
Reverts oven-sh/bun#13612

### CODE REVIEW

**Comment by jonblatho** [comment]
If I can ask, why was this reverted? I tried the canary build from #13612 and can confirm it partially fixed the issue I was encountering — it seems Bun still doesn't respect my SSH config, so I now have to specify `git@` in the repository URL in `package.json`, but when I do so it no longer attempts to resolve over HTTPS instead of SSH, so the install succeeds. Did that break something else?

**Comment by Jarred-Sumner** [comment]
@jonblatho un-reverted since, please run `bun upgrade --canary`

**Comment by jonblatho** [comment]
@Jarred-Sumner my apologies, looks like my successful install earlier was a fluke or I failed to clear some cache somewhere. Just retried with the canary build I mentioned above (`v1.1.27-canary.38 (9faaa9b9)`) and it looks like there was no change in behavior whatsoever from the original issue — `RepositoryNotFound` when `git@` isn't present in the URL, prompted for HTTPS auth when it is. The same holds true with the latest canary build, `v1.1.27-canary.58 (03de99af)`.

**Comment by jonblatho** [comment]
I guess I should also point out that the above was with no changes to my `.gitconfig` file (which does not have any specific references to our GitLab instance, as it's never been necessary) or SSH config. The only thing that needs to be enforced is that packages are resolved over SSH, not HTTPS, and therefore that the username for the SSH connection is `git`, not my own username.

For what it's worth, I did also attempt again after running `git config --global url.ssh://git@my.gitlab.instance.com/.insteadOf https://git@my.gitlab.instance.com/` to seemingly no avail. However, if any specific configuration changes are needed, please specify and I'm happy to retry.

**Pull request merged**
