### PR TITLE
rename `CallFrame.arguments_old` to `argumentsDeprecated`

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

@nektro when you want to say something is deprecated, don't add "old" or "2" to the name. That doesn't communicate useful information. It encourages adding "3" or "oldold" to the name. Instead, say "deprecated".

### CODE REVIEW

**Comment by robobun** [comment]
@Jarred-Sumner, your commit 27d171ca7a2427e26181954aa72c1c08a405e277 is building: [`#6679`](https://buildkite.com/bun/bun/builds/6679)

**Comment by paperdave** [comment]
this pr doesnt build because of changes on the main branch. instead of renaming a field, we should just delete arguments_old.

instead of renaming something to `_old`, just delete it. patches like this just eat CI and maintainer time. and when theyre large like this one, its really easy to get the code into a state where it doesnt compile.

imo prefer developing replacement api and then give that api a new name, or replace all old uses to the new api.

**Comment by nektro** [comment]
the `_old` pr was to free up the `.arguments` name for the new pattern partially described in the doc comment of CallFrame. there will be no oldold because the plan it to migrate all usages of arguments_old to a much less error prone way of parsing function arguments.

**Comment by nektro** [comment]
the new generator is now being worked on

**Pull request closed without merging**
