### PR TITLE
fix(sockets) ref count usockets context free

### PR DESCRIPTION
**Pull request by cirospaciari**
### What does this PR do?
Fixes https://github.com/oven-sh/bun/issues/10832
Fixes https://github.com/oven-sh/bun/issues/10991
Fixes https://github.com/oven-sh/bun/issues/10797
Fixes https://github.com/oven-sh/bun/issues/10772
Fixes https://github.com/oven-sh/bun/issues/10695
Fixes https://github.com/oven-sh/bun/issues/10539
Fixes https://github.com/oven-sh/bun/issues/10436

context is now ref counted, actual free is delayed until next tick

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [X] Code changes

### How did you verify your code works?

Existing tests

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
image
looks like a build issue on linux

**Comment by cirospaciari** [comment]
> image looks like a build issue on linux

Yeah probably already present in main, did not see how my chances could trigger this. I will take a look into it.

**Comment by Jarred-Sumner** [comment]
Where are the tests that would previously fail?

**Comment by robobun** [comment]
@cirospaciari, your commit bfe9b005232850f1277879bf6451ee343dcf4722 is building: [`#901`](https://buildkite.com/bun/bun/builds/901)

**Pull request closed without merging**
