### PR TITLE
Static frequency for os.cpus(); affinity and cgroup support for os.availableParallelism()

### PR DESCRIPTION
**Pull request by ruihe774**
### What does this PR do?

In this PR:
- `os.cpus()` gets static CPU frequency from `/proc/cpuinfo` as a fallback if dynamic CPU frequency from `/sys/devices/system/cpu/cpu{}/cpufreq/scaling_cur_freq` is not available, which is a common scenario in VM or container. The static CPU frequency is compatible with Node.js.
- `os.availableParallelism()` now recognize CPU affinity mask got from `sched_getaffinity()` and cgroup v2 CPU quota got from `cpu.max` controller. This is compatible with Node.js and Rust. 

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

Existing tests covered `os.cpus()` and `os.availableParallelism()`. I verified the features added in this PR by manual testing. Because testing this PR involves system-wide or process-wide setting, it is difficult to write automatic test. If you have a solution please tell me :)

JavaScript/TypeScript modules or builtins changed:
- [x] I ran `make js` and committed the transpiled changes
- [x] I or my editor ran Prettier on the changed files (or I ran `bun fmt`)
- [x] I included a test for the new code, or an existing test covers it

Zig files changed:
- [x] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [x] I or my editor ran `zig fmt` on the changed files
- [ ] I included a test for the new code, or an existing test covers it
- [x] JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed

### CODE REVIEW

**Comment by paperclover** [comment]
i think we should update `navigator.hardwareConcurrency` to match this behavior, right?

**Comment by ruihe774** [comment]
> i think we should update `navigator.hardwareConcurrency` to match this behavior, right?

I don't know the semantics of `navigator.hardwareConcurrency` in this scenario. It seems that Web spec does not define what to do with affinity or cgroup. My opinion is to keep it as is.

**Comment by ruihe774** [comment]
I’ve tried Firefox and Deno. Firefox does not regard affinity or cgroup, while Deno does.

**Comment by Jarred-Sumner** [comment]
Closing due to bitrot

**Pull request closed without merging**
