### PR TITLE
First contribution

### PR DESCRIPTION
**Pull request by 4i8**
### What does this PR do?

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?
Simple edit to my First contribution

### CODE REVIEW

**Comment by paperclover** [comment]
why this is change needed?

**Comment by 4i8** [comment]
> why this is change needed?

loop instead of repeating lines,
Simple edit and first contribution

**Comment by medz** [comment]
PR that makes no sense

**Comment by diogosilva95** [comment]
not really needed

**Comment by 4i8** [comment]
> not really needed

To prepare for what's coming🤣

**Pull request closed without merging**
