### PR TITLE
Update React fizz server

### PR DESCRIPTION
**Pull request by colinhacks**

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
Are there other differences between production and development build besides the closure compiler?

**Comment by Jarred-Sumner** [comment]
getting this error in the benchmark

don't know if that's:
- a module resolution bug in bun
- build issue with react-dom


image



repro in `bun/bench/react-hello-world`:
```bash
bun --jsx-production --define=process.env.NODE_ENV:"'production'" react-hello-world.jsx
```

```
oha http://localhost:3001 -z 5s -c 20
```

**Comment by colinhacks** [comment]
Currently it only works with `react@next` and `react-dom@next`, I'm guessing the benchmarks are using `latest`. The bundled code relies on some internals that have changed since the latest release. I'll look into trying to fix that.

**Comment by Jarred-Sumner** [comment]
There's a 23% perf gap between this build and the previous build. Will try with Bun.escapeHTML

**Comment by colinhacks** [comment]
> Are there other differences between production and development build besides the closure compiler?

The dev bundle is 9kloc instead of 6k loc, seems unused code get strips. Also `freeze` is true in the rollup config (https://rollupjs.org/guide/en/#outputfreeze) and I think some profiling is disabled/removed

**Comment by Jarred-Sumner** [comment]
Bun.escapeHTML did essentially nothing

> captureBoundaryErrorDetailsDev
> popComponentStackInDEV

There are a number of functions here which are intended to only be included in development builds 

Do you have a separate `.production` build we could try with?

**Comment by Jarred-Sumner** [comment]
7% perf gap now. Close enough, we can address that in a follow-up PR. 

For reference in your draft PR,

With Bun's ReactDOM Server build on macOS arm1:
```
❯ oha http://localhost:3001 -z 5s -c 20
Summary:
  Success rate:	1.0000
  Total:	5.0012 secs
  Slowest:	0.0077 secs
  Fastest:	0.0000 secs
  Average:	0.0002 secs
  Requests/sec:	102321.1759

  Total data:	42.46 MiB
  Size/request:	87 B
  Size/sec:	8.49 MiB

Response time histogram:
  0.000 [10001]  |■
  0.000 [40811]  |■■■■■■■
  0.000 [175510] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.000 [178298] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.000 [77296]  |■■■■■■■■■■■■■
  0.000 [19933]  |■■■
  0.000 [5344]   |
  0.000 [1478]   |
  0.000 [402]    |
  0.001 [113]    |
  0.001 [2542]   |

Latency distribution:
  10% in 0.0001 secs
  25% in 0.0002 secs
  50% in 0.0002 secs
  75% in 0.0002 secs
  90% in 0.0003 secs
  95% in 0.0003 secs
  99% in 0.0004 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0012 secs, 0.0007 secs, 0.0016 secs
  DNS-lookup:	0.0001 secs, 0.0000 secs, 0.0002 secs

Status code distribution:
  [200] 511728 responses
```


With `react-dom/server.browser` on the same machine:

```
❯ oha http://localhost:3001 -z 5s -c 20
Summary:
  Success rate:	1.0000
  Total:	5.0009 secs
  Slowest:	0.0079 secs
  Fastest:	0.0001 secs
  Average:	0.0007 secs
  Requests/sec:	29232.7949

  Total data:	12.13 MiB
  Size/request:	87 B
  Size/sec:	2.43 MiB

Response time histogram:
  0.000 [38]    |
  0.000 [23187] |■■■■■■■■■■■■
  0.001 [40043] |■■■■■■■■■■■■■■■■■■■■■
  0.001 [59202] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.001 [14094] |■■■■■■■
  0.001 [1711]  |
  0.001 [1762]  |
  0.002 [3407]  |■
  0.002 [1941]  |■
  0.002 [395]   |
  0.002 [410]   |

Latency distribution:
  10% in 0.0004 secs
  25% in 0.0005 secs
  50% in 0.0007 secs
  75% in 0.0008 secs
  90% in 0.0009 secs
  95% in 0.0012 secs
  99% in 0.0016 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0007 secs, 0.0006 secs, 0.0008 secs
  DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0001 secs

Status code distribution:
  [200] 146190 responses
```

A 3.5x perf improvement

```
// to run this:
//   bun --jsx-production react-hello-world.jsx

// This will become the official react-dom/server.bun build a little later
// It will be the default when you import from "react-dom/server"
// That will work via the "bun" package.json export condition (which bun already supports)
import { renderToReadableStream } from "react-dom/server";
const headers = {
  headers: {
    "Content-Type": "text/html",
  },
};

const App = () => (
  <html>
    <body>
      <h1>Hello World</h1>
      <p>This is an example.</p>
    </body>
  </html>
);

const port = Number(process.env.PORT || 3001);
Bun.serve({
  port,
  async fetch(req) {
    return new Response(await renderToReadableStream(<App />), headers);
  },
});

console.log(`Server running on\n  http://localhost:${port}`);
```

**Pull request merged**
