### PR TITLE
docs: add scoop installation method

### PR DESCRIPTION
**Pull request by sitiom**
### What does this PR do?

Continuation of https://github.com/oven-sh/bun/pull/7882

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### CODE REVIEW

**Comment by paperclover** [comment]
As i posted in the #9806 PR

> Before this is added, i want to solve this.
> `# Or if your CPU does not support the AVX2 instruction set. You can check by running this command:`
> 
> This should not be manual. I will look into how this can be solved for `winget` later. If it is not solvable, I don't think we should recommend `winget`'s usage for installing bun.

I'll take a look at how scoop works later and see what can be done.

**Comment by sitiom** [comment]
As mentioned in the discord server a while ago, the check has been already been added to Scoop. But I thought might as well let the users know how to check it themselves 🤔

**Comment by paperclover** [comment]
Is it possible to make so the pre_install script just downloads the correct one?

**Comment by Jarred-Sumner** [comment]
@sitiom thank you for this, but we can't in good faith add this to our docs as a recommended installation method until the `baseline` build detection is automatic

Any ideas how we can make `scoop install bun` choose the baseline build or regular build automatically, without asking users to make a decision and handle a confusing error?

**Comment by sitiom** [comment]
I think the suggestion `Please install 'bun-baseline' instead` is clear. Although if you insist, it's possible for Scoop to download both and then do the check (although that means more download bandwidth), would that be fine?

CC @chawyehsu

**Comment by Jarred-Sumner** [comment]
> I think the suggestion Please install 'bun-baseline' instead is clear.

It's clear to us, but we can't expect that from people trying Bun for the first time

> it's possible for Scoop to download both and then do the check (although that means more download bandwidth), would that be fine?

I think that is a better tradeoff, one option would be to have 3 packages: `bun`, `bun-windows-x64`, `bun-windows-x64-baseline` and then the other 2 are dependencies of `bun` and then a small script would run to detect if they support AVX2 and if so, use the x64 build and otherwise fallback to use the x64-baseline build

**Comment by chawyehsu** [comment]
> I think the suggestion `Please install 'bun-baseline' instead` is clear. Although if you insist, it's possible for Scoop to download both and then do the check (although that means more download bandwidth), would that be fine?
> 
> 
> 
> CC @chawyehsu

I agree with you. And I personally don't like the idea of downloading additional zip on-the-fly via the pre_install script （which will take much unwanted work like validating checksums in an unusual way).

If you think the way Scoop currently provides is not good enough, I'd suggest you bundling bun and bun-baseline into one single zip so we can just download that single zip (or if it's not appropriate then we can download both of the two zips simultaneously) and expose the proper exec for our users based on detected microarch. This takes 2x bandwidth but is succincter and some other packages also do this way (in the way of bundling 32bit and 64bit).

**Comment by sitiom** [comment]
Here you go:
- https://github.com/ScoopInstaller/Main/pull/5680

**Comment by paperclover** [comment]
legendary. will merge this after it lands in scoop.

**Comment by sitiom** [comment]
@paperdave Now merged 🙂

**Comment by paperclover** [comment]
incredible work

**Comment by Jarred-Sumner** [comment]
Thank you

**Pull request merged**
