### PR TITLE
Stub more of perf_hooks

### LINKED ISSUE #5804: TypeError: PerfHooks.performance.eventLoopUtilization is not a function
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 21.2.0 x86_64 i386

### What steps can reproduce the bug?

Start a basic server with Hapi library

```
import Hapi from "@hapi/hapi";

async function init() {
  const server = Hapi.server({
    port: 3000,
    host: "localhost",
  });

  server.route({
    method: "GET",
    path: "/test",
    handler: async (request, h) => {
      return h.response({ success: true }).type("application/json");
    }
  });

  await server.start();
  console.log("Server running on %s", server.info.uri);
}

init();
```

### What is the expected behavior?

The server starts

### What do you see instead?

```
TypeError: PerfHooks.performance.eventLoopUtilization is not a function. (In 'PerfHooks.performance.eventLoopUtilization()', 'PerfHooks.performance.eventLoopUtilization' is undefined)
      at new Heavy (/Users/ilyas/git/genai/node_modules/@hapi/heavy/lib/index.js:42:37)
      at new  (/Users/ilyas/git/genai/node_modules/@hapi/hapi/lib/core.js:122:21)
      at /Users/ilyas/git/genai/node_modules/@hapi/hapi/lib/server.js:22:17
      at /Users/ilyas/git/genai/src/server.js:9:17
      at init (/Users/ilyas/git/genai/src/server.js:4:19)
      at /Users/ilyas/git/genai/src/server.js:37:0
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

Fixes #5804 

This should fix the hapi issue

### How did you verify your code works?

There is a simple test

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
Fixes #5804

**Review by paperclover — APPROVED** [review]
lstm

**Comment by OleksandrKucherenko** [comment]
> NotImplementedError: perf_hooks.monitorEventLoopDelay is not yet implemented in Bun.

**Comment by LukasDeco** [comment]
I am still seeing a similar error. Running bun 1.0.26. 
```
NotImplementedError: perf_hooks.monitorEventLoopDelay is not yet implemented in Bun.
```

**Pull request merged**
