### PR TITLE
fix dns lookup for 0.0.0.0

### PR DESCRIPTION
**Pull request by sirenkovladd**
### What does this PR do?

Fixes: https://github.com/oven-sh/bun/issues/4338
`host_ptr` in `getAddrInfo` was null

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [X] Code changes

### How did you verify your code works?

- [X] I ran `make js` and committed the transpiled changes
- [X] I or my editor ran Prettier on the changed files (or I ran `bun fmt`)
- [X] I included a test for the new code, or an existing test covers it

- [ ] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [X] I or my editor ran `zig fmt` on the changed files
- [X] I included a test for the new code, or an existing test covers it
- [ ] JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed

### CODE REVIEW

**Review by Jarred-Sumner — APPROVED** [review]
Thank you. Let's merge after tests run

**Comment by sirenkovladd** [comment]
@Jarred-Sumner finished)

**Comment by Jarred-Sumner** [comment]
looks like it crashed in the node-dns tests before it finished executing:

image

**Comment by sirenkovladd** [comment]
Hmm very interesting because I built on my mac m1 and everything is fine but when I download the artifact from the ci cd sometimes it tests successfully but mostly this error
`[1]    92342 bus error  ./packages/bun-darwin-aarch64/bun-ci test test/js/node/dns`

(I can send my artifacts for comparison)

**Comment by sirenkovladd** [comment]
Maybe you know why this happens?

**Comment by sirenkovladd** [comment]
@Jarred-Sumner, it's not a problem because of my MR
I see this problem here

https://github.com/oven-sh/bun/actions/runs/5984066727/job/16235121583
https://github.com/oven-sh/bun/actions/runs/5983848284/job/16234593599
https://github.com/oven-sh/bun/actions/runs/5981455277/job/16229663965
https://github.com/oven-sh/bun/actions/runs/5981152652/job/16229169404

**Comment by sirenkovladd** [comment]
@Jarred-Sumner

**Pull request closed without merging**
