### PR TITLE
fix(nodevm): align behavior with node

### LINKED ISSUE #6272: `vm.runInThisContext` Context must be an object
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

`bun install requirejs`
`echo "const x = require('requirejs');" > index.js`
`bun index.js`

### What is the expected behavior?

No `TypeError`

### What do you see instead?

```
57 |         readFile = function (path) {
58 |             return fs.readFileSync(path, 'utf8');
59 |         };
60 | 
61 |         exec = function (string, name) {
62 |             return vm.runInThisContext(this.requirejsVars.require.makeNodeWrapper(string),
                       ^
TypeError: Context must be an object
      at exec (/Users/artemivanov/Sites/x/node_modules/requirejs/bin/r.js:62:19)
      at setBaseUrl (/Users/artemivanov/Sites/x/node_modules/requirejs/bin/r.js:30248:12)
      at /Users/artemivanov/Sites/x/node_modules/requirejs/bin/r.js:30338:8
      at /Users/artemivanov/Sites/x/node_modules/requirejs/bin/r.js:30423:21
      at globalThis (/Users/artemivanov/Sites/x/node_modules/requirejs/bin/r.js:30431:60)
      at require (:1:20)
      at /Users/artemivanov/Sites/x/index.js:1:6
      at globalThis (/Users/artemivanov/Sites/x/index.js:1:6)
```

### Additional information

_No response_

### LINKED ISSUE #13589: Can't set context properties when using `Script.runInNewContext`
### What version of Bun is running?

1.1.26+0a37423ba

### What platform is your computer?

Microsoft Windows NT 10.0.22635.0 x64

### What steps can reproduce the bug?

```
bun -e 'import vm from "node:vm";
const script = new vm.Script("returnValue = \"bunny\";");
const context = vm.createContext();
script.runInNewContext(context);
console.log(context.returnValue);'
```

### What is the expected behavior?

I expect to get "bunny"

### What do you see instead?

undefined

### Additional information

works fine on Node:

```
node -e 'const vm = require("node:vm");
const script = new vm.Script("returnValue = \"bunny\";");
const context = vm.createContext();
script.runInNewContext(context);
console.log(context.returnValue);'
```

this issue makes bun incompatible with [semantic-release](https://github.com/semantic-release/semantic-release) (you can't run it with the `--bun` flag) because it [uses](https://github.com/semantic-release/semantic-release/blob/01f95fd9032e1b15b7280fbc59e67063d11b836b/bin/semantic-release.js#L28) [find-versions](https://github.com/sindresorhus/find-versions), which [uses](https://github.com/sindresorhus/find-versions/blob/a1b377dd3d887964470f42202d07ec54314595a2/index.js#L10) [super-regex](https://github.com/sindresorhus/super-regex), which [uses](https://github.com/sindresorhus/super-regex/blob/fba5633210483b33c26a106bf54a8e051d6fa8df/index.js#L56) [function-timeout](https://github.com/sindresorhus/function-timeout), which [uses](https://github.com/sindresorhus/function-timeout/blob/12471c7f085b034c3b2432a223376e60173ec43a/index.js#L3) mentioned functionality

### LINKED ISSUE #13594: Can't change global variable values when using `vm.runInThisContext`
### What version of Bun is running?

1.1.26+0a37423ba

### What platform is your computer?

Microsoft Windows NT 10.0.22635.0 x64

### What steps can reproduce the bug?

```
bun -e 'const vm = require("node:vm");
global.globalVar = "initial value";
vm.runInThisContext("globalVar = \"vm\";");
console.log(globalVar);'
```

### What is the expected behavior?

I expect to see `vm`

### What do you see instead?

initial value

### Additional information

works fine on Node:

```
node -e 'const vm = require("node:vm");
global.globalVar = "initial value";
vm.runInThisContext("globalVar = \"vm\";");
console.log(globalVar);'
```

### PR DESCRIPTION
**Pull request by SunsetTechuila**
### What does this PR do?

fixes #13589
fixes #13594
fixes #6272

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

I wrote automated tests

### Changes:

- `script.runInThisContext` & `vm.runInThisContext` don't take context as an argument
- `vm.runInThisContext` operates in global context
- `script.runInNewContext` operates in it's own context
- `vm.runInThisContext`, `vm.runInContext`, `vm.runInContext` take a string as the options arg

relevant node documentation: https://nodejs.org/api/vm.html

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
fixed

**Comment by Jarred-Sumner** [comment]
Looks like the crypto key object test is throwing a ReferenceError

**Comment by SunsetTechuila** [comment]
yes, it tries to use local context for runInNewContext

**Comment by SunsetTechuila** [comment]
btw `crypto.key-objects.test.ts` has bazillion ts errors

**Comment by Jarred-Sumner** [comment]
Thank you

**Pull request merged**
