### PR TITLE
promisify implementation

### LINKED ISSUE #15201: setTimeout hasn't promisify implementation
### What version of Bun is running?

1.1.34+5e5e7c60f

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

require('util').promisify(setTimeout)(100, 'ok').then(console.log);

### What is the expected behavior?

node test.js
>ok

### What do you see instead?

Image

### Additional information

I've revised  https://github.com/oven-sh/bun/issues/4361 and https://github.com/oven-sh/bun/issues/7148. But it seems in the current `bun` version it was not fixed.

### PR DESCRIPTION
**Pull request by ippsav**
### What does this PR do?

Fixes #15201

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
This makes the util.promisify function a little bit slower on every call unrelated to setTimeout or setInterval or timers.

Instead of doing that, can we make this work in ZigGlobalObject.cpp when we define the setTimeout and setInterval functions?

**Review by Jarred-Sumner — CHANGES_REQUESTED** [review]
This makes the util.promisify function a little bit slower on every call unrelated to setTimeout or setInterval or timers.

Instead of doing that, can we make this work in ZigGlobalObject.cpp when we define the setTimeout and setInterval functions?

**Comment by ippsav** [comment]
@Jarred-Sumner, I'll need some time to properly understand the internals of JSC and how all the components interact with each other before implementing this change. Would it be possible to merge this current PR to address the immediate issue, and then I can create a follow-up PR with your suggested optimization once I've familiarized myself better with all what's JSC related ?

**Comment by tannal** [comment]
Hi, I think all we need to do is set `setTimeout[Symbol.for('nodejs.util.promisify.custom')]` to `setTimeoutPromise` when we define the setTimeout function.

Same for setInterval.
```js
console.log(setTimeout[Symbol.for('nodejs.util.promisify.custom')])
```
Run this script with node and bun, and you can see the difference.

**Comment by Jarred-Sumner** [comment]
Closing in favor of #15230

**Pull request closed without merging**
