### PR TITLE
Add tests for `bun test` with preload scripts

### PR DESCRIPTION
**Pull request by jakeboone02**
Per @Jarred-Sumner [in this Discord chat](https://discord.com/channels/876711213126520882/1092938757428219934/1092942936469143552), tests exist for the `preload` config for `bun run` but not for `bun test`. This PR adds those missing tests. (It also updates the `cowsay` example on the README to be compatible with `zsh`.)

### CODE REVIEW

**Review by Jarred-Sumner — APPROVED** [review]
LGTM

**Review by Jarred-Sumner — CHANGES_REQUESTED** [review]
after manually testing it, seems there are two issues:
1) `stdout` should be `stderr`, we log test output on stderr
2) bunfig.toml version isn't actually loading in tests, separate bug which i will quickly fix


edit: we are loading it in tests, but only when `test.preload` and not `preload`

**Comment by jakeboone02** [comment]
Thanks for looking at it. I make the `stderr` update.

**Comment by jakeboone02** [comment]
Oh just saw your edited review comment. Should I change the bunfig.toml definition in the test?

**Comment by Jarred-Sumner** [comment]
Thanks

**Pull request merged**
