### PR TITLE
Add `TextDecoderStream`, `TextEncoderStream`, and `TextDecoder.decode("", { stream: true})`

### LINKED ISSUE #5542: TextDecoder doesn't implement "stream" option
### What version of Bun is running?

1.0.2

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

```js
const decoder = new TextDecoder('utf-8');
const first = decoder.decode(new Uint8Array([226, 153]), { stream: true });
const second = decoder.decode(new Uint8Array([165]), { stream: true });
console.log({first, second});
```

### What is the expected behavior?

`first` should be an empty string and `second` should return a `♥` string

### What do you see instead?

Both `first` and `second` are populated with incorrect values

### Additional information

_No response_

### LINKED ISSUE #5648: Add TextDecoderStream and TextEncoderStream
`TextDecoderStream` and `TextEncoderStream` are missing

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
Adds `TextDecoderStream` and `TextEncoderStream` to globals. Part of implementing this required the `stream: true` option for `TextDecoder`.

Also adds support for `new TextDecoder("utf-16be")`.

closes #5648 
closes #5542 

### How did you verify your code works?
A bunch of tests from webkit and node

### CODE REVIEW

**Comment by robobun** [comment]
@dylan-conway, your commit 9ea3d7d406439512a6e5d5ee75481fa8db918504 is building: [`#1356`](https://buildkite.com/bun/bun/builds/1356)

**Comment by ctjlewis** [comment]
Thank you king!

**Comment by zoto-ff** [comment]
image

**Comment by notKamui** [comment]
image

**Pull request merged**
