### PR TITLE
command correction in vite.md

### PR DESCRIPTION
**Pull request by mayurmarvel**
The Command is specied as "bunx create-vite my-app" . The correct command is "bun x create-vite my-app"

### What does this PR do?

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### CODE REVIEW

**Comment by LeCarteloo** [comment]
Both commands work the same. (for Ubuntu and WSL2)

**Comment by gtrabanco** [comment]
Someone reported bunx was not installed, maybe he has same issue and though bunx was deleted 😅

**Comment by mayurmarvel** [comment]
Do we have to install bunx seperately? I have installed bun and "bun x " is working fine but "bunx" is not working

**Comment by gtrabanco** [comment]
> Do we have to install bunx seperately? I have installed bun and "bun x " is working fine but "bunx" is not working

No, it is a bug I think. Was reported in discord so probably will be solved with next update.

https://github.com/oven-sh/bun/issues/4717

**Pull request closed without merging**
