### PR TITLE
[WIP] test bun-mac-x64-baseline against macos-10.15

### PR DESCRIPTION
**Pull request by kzc**
Not intended to be committed.
Just want to see which tests fail on macos-10.15.

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
There will be many, we recently added a lot more tests and `main` isn't green yet. I would expect at least 30 test failures

**Comment by Jarred-Sumner** [comment]
you'll need to make a change to a file in test/ or src/ for it to build though

**Comment by kzc** [comment]
Cannot get to the Test phase for macos-10.15 on x64.

The macos-10.15 x64 `mach_vm_offset_t` compile errors were resolved by 44c0972e9966fd8e85d07b27077a2ea52b0e6fc1 but the Link stage failed with:

```
... hundreds of similar warnings ...
ld: warning: linking module flags 'SDK Version': IDs have conflicting values ('[2 x i32] [i32 12, i32 1]' from /Users/runner/work/_temp/bun-webkit/lib/libbmalloc.a(pas_virtual_range.c.o) with '[2 x i32] [i32 11, i32 1]' from ld-temp.o)
ld: warning: object file (/tmp/lto.o) was built for newer macOS version (11.0) than being linked (10.15)
Undefined symbols for architecture x86_64:
  "_removefileat", referenced from:
      _NodeJSFSPrototype__rmSync in bun.o
  "___ulock_wait2", referenced from:
      _debug.panicImpl in bun.o
ld: symbol(s) not found for architecture x86_64
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bun-link-lld-release] Error 1
Error: Process completed with exit code 2.
```

I don't know how to proceed.

Github actions support for macos-10.15 will apparently be [completely removed by 2023-03-31](https://github.com/actions/runner-images/issues/5583#issuecomment-1426004850).

**Comment by Jarred-Sumner** [comment]
If `removefileat` isn't supported, we'll need a polyfill in here:

https://github.com/oven-sh/bun/blob/cb1b88174666aaef9e7fc6cadbd77f34ce331c04/src/bun.js/node/node_fs.zig#L3605-L3609

`ulock_wait2` I'm not as sure about, I think we might need to pass the macOS minimum version to Zig in build.zig

**Comment by kzc** [comment]
> If `removefileat` isn't supported, we'll need a polyfill in here:

Interesting... it's a weakly linked symbol in macos-11 that just wasn't encountered by simple testing of the latest darwin bun release on macos 10.14 x64 Mojave.

`removefile` *is* present on macos-10.14, so the line in question can simply be replaced by:

```diff
- if (Maybe(Return.Rm).errnoSys(bun.C.darwin.removefileat(std.os.AT.FDCWD, dest, null, flags), .unlink)) |errno| { 
+ if (Maybe(Return.Rm).errnoSys(bun.C.darwin.removefile(dest, null, flags), .unlink)) |errno| { 
```

if I read the man page at https://keith.github.io/xcode-man-pages/removefileat.3.html correctly.

**Comment by Jarred-Sumner** [comment]
> > If `removefileat` isn't supported, we'll need a polyfill in here:
> 
> Interesting... it's a weakly linked symbol in macos-11 that just wasn't encountered by simple testing of the latest darwin bun release on macos 10.14 x64 Mojave.
> 
> `removefile` _is_ present on macos-10.14, so the line in question can simply be replaced by:
> 
> ```diff
> - if (Maybe(Return.Rm).errnoSys(bun.C.darwin.removefileat(std.os.AT.FDCWD, dest, null, flags), .unlink)) |errno| { 
> + if (Maybe(Return.Rm).errnoSys(bun.C.darwin.removefile(dest, null, flags), .unlink)) |errno| { 
> ```

That sounds good to me. It will need to be added to `src/darwin_c.zig`, something like

```zig
pub extern fn removefile(path: [*c]const u8, state: ?*removefile_state_t, flags: u32) c_int;
```

**Comment by kzc** [comment]
Added the `removefile` change in 0e17b15f36e789dd3ba28429e07511cc72417589.

As you may have guessed, I don't have a local repo and I'm committing blindly using the github web UI to make changes a file at a time. I just wanted to take advantage of github actions support for `macos-10.15` while it's still available for another week or so.

Feel free to take over this pull request for `ulock_wait2` and other macos-10.x build issues.

**Comment by kzc** [comment]
Did some digging... the unresolved `___ulock_wait2` from the link:
```
Undefined symbols for architecture x86_64:
  "___ulock_wait2", referenced from:
      _debug.panicImpl in bun.o
ld: symbol(s) not found for architecture x86_64
```
does indeed come from the zig runtime:

https://github.com/ziglang/zig/blob/5df31f3ef3d2c4640fa2c7fc9b03c83c6a8606ae/lib/std/debug.zig#L367-L369

which in turn invokes:

https://github.com/ziglang/zig/blob/5df31f3ef3d2c4640fa2c7fc9b03c83c6a8606ae/lib/std/Thread/Futex.zig#L165-L219

~If `___ulock_wait2` is not found then the code attempts to use `___ulock_wait`.  Neither of these functions exist on macos-10.14.~

**Edit:** the comment above is incorrect.

**Comment by kzc** [comment]
Although there's no function declaration for `ulock_wait` and `ulock_wake` on macos 10.14, their syscalls do exist:

```
$ cd /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include
$ find . -name '*.h' -print | xargs grep ulock_
./sys/syscall.h:#define	SYS_ulock_wait     515
./sys/syscall.h:#define	SYS_ulock_wake     516
```

**Comment by kzc** [comment]
It's possible that the polyfill of `__ulock_wait2` in the last commit needs to invoke a syscall of `__ulock_wait` rather than an external function. Let's see what happens when it's built and run.

**Comment by kzc** [comment]
`bun-macOS-x64-baseline / macOS Link` worked. 

> I would expect at least 30 test failures

There were 24 files with test failures on `bun-darwin-x64-baseline`.

Not sure how to view the test failures in some files such as `test/js/node/child_process/child_process-node.test.js`.  I must be missing something obvious.

I was unable to compare to the other targets' test results because their Test jobs were either cancelled or experienced problems.

**Comment by kzc** [comment]
The goal of this pull request was accomplished. I don't plan to work on it further. If anyone wishes to take over this pull request - feel free. Otherwise I'll close it.

**Comment by Jarred-Sumner** [comment]
@kzc want to chat about contracting with Oven? free to email me jarred@oven.sh

**Comment by kzc** [comment]
Looks like github actions support for macos-10.15 was [dropped](https://github.com/actions/runner-images/commit/6a893d200c2728607f6132c8218a657a6496eb3f) so this is no longer easily testable.

fwiw, the latest `bun build` on macos-10.x will not work without a `__ulock_wait2` polyfill.  However, a jerry-rigged dylib with canary appears to do the trick for the few trying to run bun on that unsupported OS version.

**Comment by kzc** [comment]
@Jarred-Sumner Just curious - what's the point of `bun-macOS-x64-baseline`?

I downloaded the bun binary from the `bun-darwin-x64` artifact of `bun-macOS-x64` https://github.com/oven-sh/bun/actions/runs/4867421640 and it ran equally well on macos-10.14 x64.

**Comment by Jarred-Sumner** [comment]
`bun-macOS-x64-baseline` has no SIMD 

https://github.com/oven-sh/bun/issues?q=is%3Aissue+illegal+instruction+is%3Aclosed

**Pull request closed without merging**
