### PR TITLE
Fix bundling for bun not using ascii_only

### LINKED ISSUE #9559: When using bun to build a binary file, the Chinese key in the js object will be garbled.
### What version of Bun is running?

1.0.33

### What platform is your computer?

Linux 5.15.0-86-generic x86_64 x86_64

### What steps can reproduce the bug?

{C792D954-4A15-4070-A390-D47F11D3FFE1}

build
`bun build ./a.ts --compile --outfile test`
execute
`./test`

### What is the expected behavior?

Snipaste_2024-03-22_15-29-20

### What do you see instead?

Snipaste_2024-03-22_15-28-37

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by pfgithub**
### What does this PR do?

Fixes #9559

In printWithWriterAndPlatform(), its NewPrinter call was always setting ascii_only to false, but that means when bundling for the bun target, the code is not emitted as ascii only and there will be errors when running because it tries to run as latin1.

This code

```js
console.log(JSON.stringify({我: "a"}));

const 我 = "b";
console.log(JSON.stringify({我}));
```

When built with `bun build --target bun code.js` now emits:

```js
// @bun
// code.js
console.log(JSON.stringify({ "\u{6211}": "a" }));
var \u{6211} = "b";
console.log(JSON.stringify({ "\u{6211}": \u{6211} }));
```

instead of:

```js
// @bun
// code.js
console.log(JSON.stringify({ "我": "a" }));
var 我 = "b";
console.log(JSON.stringify({ "我": 我 }));
```

It also works with `bun build --compile`.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

Added a regression test for the issue

It tests `bun build --target bun` and not `bun build --compile` because compile takes a second and they're both the same issue.

If Zig files changed:

- [ ] N/A I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [ ] I included a test for the new code, or an existing test covers it
- [ ] N/A JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed
- [x] I wrote TypeScript/JavaScript tests and they pass locally (`bun-debug test test-file-name.test`)

### CODE REVIEW

**Review by paperclover — APPROVED** [review]
today i learned `\u{6211}` is valid identifier

**Comment by Jarred-Sumner** [comment]
Thank you for this.

Can you add a test for `bun build --compile` as well? You can see the tests in `bundler_compile` for an example

**Comment by pfgithub** [comment]
Added one in bundler_compile

**Comment by pfgithub** [comment]
I don't think any of the CI failures are my fault

**Comment by Jarred-Sumner** [comment]
Agreed, thank you for this

**Pull request merged**
