### PR TITLE
chore: better build workflow

### PR DESCRIPTION
**Pull request by xhyrom**
> **Warning**
> Haven't tested, can't test it

Every `matrix.settings` element will run as new job

Added `bun-build.yml` that builds macos + linux

Not sure if it works

### CODE REVIEW

**Comment by xhyrom** [comment]
okay, it should work but i cant test it @Jarred-Sumner

**Comment by xhyrom** [comment]
I'll resolve conflicts today/after vacation

**Comment by xhyrom** [comment]
resolved, ready for review *i hope it will works*

**Comment by xhyrom** [comment]
I'll resolve conflicts today/tomorrow

**Comment by Electroid** [comment]
Thanks for working on this. Yes it would be great to refactor our workflows to be composite. It has changed quite a bit since you last worked on it, so going to close this out for now. Feel free to open a new issue if you want to tackle this again.

**Pull request closed without merging**
