### PR TITLE
#941 fix

### PR DESCRIPTION
**Pull request by pepper-lees**
2nd attempt... I wiped changes from my branch, forgetting that I still had an unmerged PR open, and it automatically closed PR #998 

> Issue was from wrapping `assert` in an ESM-style `export * from assert` statement. ESBuild, instead of copying the exported variable straight from `assert`, created a new object and populated it with all the properties. This lost the handy dandy fact that `assert` was actually a function at heart, not an object.

### CODE REVIEW

**Comment by zhuzilin** [comment]
This should also relates to #940.

I don't think the current fix works though... Have you tried to compile and run it? I got:
```bash
root ➜ ~/test_js $ cat assert.js 
const assert = require("assert")
console.log(typeof assert)
assert(true)
root ➜ ~/test_js $ bun run assert.js 
object
1 | const assert = require("assert")
2 | console.log(typeof assert)
3 | assert(true)
   ^
TypeError: assert is not a function. (In 'assert(true)', 'assert' is an instance of Object)
      at /root/test_js/assert.js:3:0
```

**Review by evanwashere — CHANGES_REQUESTED** [review]
this breaks esm import

**Comment by pepper-lees** [comment]
> this breaks esm import

@evanwashere Example? It works perfectly fine for me. The following behave exactly the same:

```js
var assert = require('assert');

assert(true);
console.log(assert.ok === assert);
assert(false);
```

```js
import assert from 'assert';

assert(true);
console.log(assert.ok === assert);
assert(false);
```

**Comment by Electroid** [comment]
Thanks for submitting this PR, we fixed this a while ago.

**Pull request closed without merging**
