### PR TITLE
Avoid creating a Napi handle scope within a finalizer

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

This makes napi handle scopes optional, and we ignore them when they're not set.

Fixes https://discord.com/channels/876711213126520882/1282959007589601280/1282959007589601280

This mitigates a crash where a napi package creates a handle scope within a finalizer. Any object allocation within that finalizer would still fail, but the act of creating a handle scope at all inside a finalizer fails since it is an allocation. 

### How did you verify your code works?

I verified the crash is fixed manually.

This needs a test. The test would do something like:
- Create a napi ref wrapping an object
- The napi ref's finalizer function should open a handle scope
- Allocate repeatedly until the napi ref's finalizer is called

### CODE REVIEW

**Comment by robobun** [comment]
@Jarred-Sumner, your commit 7cb2bad7999529e20e9ce18af8545321720d80d0 is building: [`#3250`](https://buildkite.com/bun/bun/builds/3250)

**Comment by 190n** [comment]
It looks like nodejs/node-addon-api#1409 will (once it lands in a release) also fix this, as they now [intentionally defer the execution of finalizers instead of relying on Node.js to do it](https://github.com/nodejs/node-addon-api/pull/1409/files#diff-cd0b229bcaf532206661e2ee1a603a7f60ac22ecfcb239920f6b42a34d909f34R34-R50):

```cpp
#if (defined(NAPI_EXPERIMENTAL) &&                                             \
     defined(NODE_API_EXPERIMENTAL_HAS_POST_FINALIZER))
template <napi_finalize finalizer>
inline void PostFinalizerWrapper(node_api_nogc_env nogc_env,
                                 void* data,
                                 void* hint) {
  napi_status status = node_api_post_finalizer(nogc_env, finalizer, data, hint);
  NAPI_FATAL_IF_FAILED(
      status, "PostFinalizerWrapper", "node_api_post_finalizer failed");
}
#else
template <napi_finalize finalizer>
inline void PostFinalizerWrapper(napi_env env, void* data, void* hint) {
  finalizer(env, data, hint);
}
#endif
```

But this solution will do for now. I'll write a test -- I might see if we can pass a JS callback into the NAPI functions that calls `Bun.gc` instead of trying to trigger it via a bunch of allocations, as that will make the other GC tests faster too. But I'll have to make sure that that does actually reproduce GC bugs.

**Review by 190n — CHANGES_REQUESTED** [review]
needs a test

**Review by 190n — APPROVED** [review]

**Review by 190n — CHANGES_REQUESTED** [review]
the tests crash node

**Pull request merged**
