### PR TITLE
`bun install` fix Git SSH URLs

### LINKED ISSUE #4068: bun install with Gitlab repository in dependencies not working
### What version of Bun is running?

0.7.3

### What platform is your computer?

Linux 6.4.7-arch1-1 x86_64

### What steps can reproduce the bug?

1. `bun init`
2. Add Gitlab dependency like this, in `package.json`:
```
"dependencies": {
    "package": "git+ssh://git@gitlab.example.com:foobar.git"
}
```
3. `bun install`

### What is the expected behavior?

Gitlab dependency should be installed without errors.

### What do you see instead?

```
bun install v0.7.3 (a9b3d583)
  🔍 Resolving [1/1] 
error: InstallFailed cloning repository for "<package-name>"
error: "git clone" for "<package-name>" failed
error: "git clone" for "<package-name>" failed
```

### Additional information

1. HTTPS protocol works, SSH doesn't.
`git+https://gitlab.example.com/foobar.git` ✅ 
`git+ssh://git@gitlab.example.com:foobar.git` ❌ 

2. `npm install` works just fine.

3. I would assume this might be an issue on Github as well, haven't tested though.

### PR DESCRIPTION
**Pull request by Parzival-3141**
### What does this PR do?

Closes #4068

`npm` allows SSH and SCP style URLs to have a `:` between the host and path, but `git` will not accept URLs like that. So we need to do a small conversion between the two.
E.g.  `git+ssh://git@example.com:path/to/repo` -> `git+ssh://git@example.com/path/to/repo`

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?
I wrote automated tests

- [x] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [x] I or my editor ran `zig fmt` on the changed files
- [x] I included a test for the new code, or an existing test covers it

### CODE REVIEW

**Comment by Parzival-3141** [comment]
`filesink.test.ts`,`postgres.test.ts`, and `prisma.test.ts` are the only tests that are blocking this PR. I think the rest are issues with `macOS-x64` builds in general.

**Comment by h2oearth** [comment]
I'm looking forward to this PR: –). We can not use bun in some repos :-(, because of the `git+ssh://git@github.com` issue

**Comment by timeturnback** [comment]
how was this going guys

**Comment by Jarred-Sumner** [comment]
This was addressed some time ago

**Pull request closed without merging**
