### PR TITLE
feat(vscode-extension): test support

### PR DESCRIPTION
**Pull request by samuelgja**
### What does this PR do?

**Bun Vscode extension test support**
It is a little bit inspired by rust vs code extension, where the user can run tests directly in the editor.

I created this functionality a few weeks ago and found it helpful in my projects, so maybe it can be added to the extension, or maybe not :D

- ability to run test directly from vscode opened editor:
Screenshot 2024-09-01 at 12 38 56

- run test for whole file via vscode settings command:
Screenshot 2024-09-01 at 12 41 04

- user defined test file pattern matcher:
Screenshot 2024-09-01 at 12 41 35

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes
### Code changes

- added new test provider [packages/bun-vscode/src/features/tests/index.ts](https://github.com/oven-sh/bun/compare/main...samuelgja:bun:main#diff-a0ef2cf3fa6ec77288d3cf68151458a0b3c787683cc7071cadc8e71607725d87) - handling run (watch) test command + code lens
- code-lens - add `run test` `watch test` buttons for each test in currently opened file
- update vscode extension package.json to support `run test` and `watch test` for the current open file
- update vscode extension package.json to support new `bun.test.filePattern` extension setting (pattern for matching the test files)
### How did you verify your code works?
Unfortunately, there is no test method in bun vs-code extension code base. So just manually :(

### CODE REVIEW

**Comment by chrisbbreuer** [comment]
Not going to lie, I was just about to create a separate vscode extension just for this to improve our internal testing flow some, and I was going to copy much from "Better PHPUnit", so I very much appreciate this! ❤️

**Comment by marviobezerra** [comment]
Unit tests are a key component in our development process. Please bring it to the next level. I’d love to see it working inside vscode ide.

**Comment by DaveWelling** [comment]
Hmm.  It's disappointing that they haven't merged this.  Have you considered just releasing it as a new VsCode extension?

**Comment by samuelgja** [comment]
> Hmm. It's disappointing that they haven't merged this. Have you considered just releasing it as a new VsCode extension? Alternatively, if instructions for just installing it from code are easy, maybe you could drop them in here, and people could get going with it. In any case, thanks for doing this!

@DaveWelling Instruction for install locally are pretty easy:
1. download my bun forked repo: https://github.com/samuelgja/bun or git@github.com:samuelgja/bun.git
2. Navigate to `bun/packages/bun-vscode`
3. `bun install`
4. `bun run build` - this will build extension (.vsix) file inside extension folder
5.  In vscode just install extension from .vsix file (screenshot) 
Screenshot 2024-11-02 at 12 41 57

**Comment by samuelgja** [comment]
> Unit tests are a key component in our development process. Please bring it to the next level. I’d love to see it working inside vscode ide.

Yes, testing vs code extension is kinda pain in a**. In vscode itself I think the tests are considered more like "integration tests", than a unit, as it will run the whole vscode instance and test "functionality" in this new testing window.

I can try something - more like unit.

**Comment by Pckool** [comment]
So this was just killed? I was really hoping to get bun working officially with the vscode test explorer.

**Pull request closed without merging**
