### PR TITLE
feat(fs/readdir): Impl. recursive option

### LINKED ISSUE #3871: implement nodejs readdir recursive
### What is the problem this feature would solve?

Recursive directory reading

### What is the feature you are proposing to solve the problem?

Nodejs added the recursive option to fs.readdir in v20.1.0: https://nodejs.org/api/fs.html#fsreaddirpath-options-callback

```js
await fs.readdir('.', { recursive: true });
```

Would be great if bun could support this :)

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by v3nntrnx**
### What does this PR do?

This implements the new fs.readdir option recursive, which recursively walks over a directory (added in node.js since v20.1.0: https://nodejs.org/api/fs.html#fsreaddirpath-options-callback)

### How did you verify your code works?

Run it on my local hardware (ext4), i'll comment my attempts to run it in vm's and on different hardware in the discussion.

I wrote automated tests.

Thanks to @InKryption for helping me
Closes #3871

### CODE REVIEW

**Comment by v3nntrnx** [comment]
Ubuntu, QEMU (gnome boxes), one btrfs drive
image

**Comment by v3nntrnx** [comment]
Same machine as above, across multiple btrfs drives
image

**Comment by v3nntrnx** [comment]
WSL (Debian, Windows 10 Home as host)

image

**Comment by Jarred-Sumner** [comment]
This code looks like it works but I kind of wish it was done by sending in chunks to JS instead of allocating the whole thing without any limits. There are various cases where this can cause OOM. We should have a test that it does not follow symlinks?

**Comment by v3nntrnx** [comment]
> We should have a test that it does not follow symlinks? 

I'll test it when I'm home

**Comment by v3nntrnx** [comment]
Test for symlinks passes
image

**Comment by v3nntrnx** [comment]
Symlink test:

Ubuntu, QEMU (gnome-boxes)
image

WSL Debian, Windows 10 home
image

**Pull request closed without merging**
