### PR TITLE
feat(bun/test): Implement "toSatisfy" & "toIncludeRepeated" (fwup)

### PR DESCRIPTION
**Pull request by v3nntrnx**
(fwup) stands for follow up, because I couldn't fix merge conflicts on my [first PR](https://github.com/oven-sh/bun/pull/3268/)

----

_toSatisfy:_

`expect(value).toSatisfy(function)`, the function passed to "toSatisfy" function is called with the value in expect, so it's almost the same as calling:

`expect(function(value)).toBeTrue();`
More about it: https://vitest.dev/api/expect.html#tosatisfy

What I already have done for toSatisfy:

- [x] Types
- [x] Testing
- [x] Implement toSatisfy itself

---

_toIncludeRepeated:_

More about it: https://jest-extended.jestcommunity.dev/docs/matchers/string/#toincluderepeatedsubstring-times

What I already have done for toIncludeRepeated:

- [x] Types
- [x] Testing
- [x] Implement toIncludeRepeated itself

<sub>_Huge thanks to @inKryption for helping me with toIncludeRepeated() <3_</sub>

### CODE REVIEW

**Comment by simylein** [comment]
If the code quality is ok, can we merge this before there are unfixable merge conflicts again?

**Comment by v3nntrnx** [comment]
> If the code quality is ok, can we merge this before there are unfixable merge conflicts again?

Just to mention, it's not unfixable but rather lack of my git skills. And for me creating a new pr was easier.

**Comment by simylein** [comment]
You are of course right, I just wanted those matchers to land in the next release.

**Comment by Jarred-Sumner** [comment]
Thank you

**Pull request merged**
