### PR TITLE
fix(requestIP): fix type cast from binary to text format for IPv4.

### PR DESCRIPTION
**Pull request by Hanaasagi**
### What does this PR do?

Close: #6668

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

Manual testing: Use another device to request the server and check the request IP.

test code:
```JavaScript
const server = Bun.serve({
    hostname: "0.0.0.0",
    port: 3000,
    development: false,
    async fetch(request) {
        console.log("IP:", this.requestIP(request));
        return new Response("Ok!");
    },
});

console.log(`Listening on 0.0.0.0: ${server.port}`);
```

### CODE REVIEW

**Comment by paperclover** [comment]
wow, `static_cast<unsigned char>` is not what i expected.

**Comment by Hanaasagi** [comment]
@paperdave  Sorry, I didn't understand. Should I change it to this?


```c++
      unsigned char *ub = (unsigned char *) b;
      length = snprintf(b, 64, "%u.%u.%u.%u", ub[0], ub[1], ub[2], ub[3]);

```

Just like what's done in `AsyncSocket::addressAsText`.

https://github.com/oven-sh/bun/blob/2b8aae05d1e95b85c7869f15567a29162106110c/packages/bun-uws/src/AsyncSocket.h#L219-L223

Or using `ares_inet_ntop AF_INET`?

**Comment by cirospaciari** [comment]
> @paperdave Sorry, I didn't understand. Should I change it to this?
> 
> ```c++
>       unsigned char *ub = (unsigned char *) b;
>       length = snprintf(b, 64, "%u.%u.%u.%u", ub[0], ub[1], ub[2], ub[3]);
> ```
> 
> Just like what's done in `AsyncSocket::addressAsText`.
> 
> https://github.com/oven-sh/bun/blob/2b8aae05d1e95b85c7869f15567a29162106110c/packages/bun-uws/src/AsyncSocket.h#L219-L223
> 
> Or using `ares_inet_ntop AF_INET`?

Thinking in edge cases probably `ares_inet_ntop` is safer

**Comment by Hanaasagi** [comment]
Fixed. But indeed, I think there isn't much difference. The root cause of this bug is that we need to convert `char` to `unsigned char` first and then format it as `%u`. `ares_inet_ntop` does it the same way.

https://github.com/c-ares/c-ares/blob/0e7a5dee0fbb04080750cf6eabbe89d8bae87faa/src/lib/inet_ntop.c#L81-L93

**Review by cirospaciari — APPROVED** [review]

**Comment by cirospaciari** [comment]
Thank you

**Pull request merged**
