### PR TITLE
Chore - quick note on dependencies for C++

### PR DESCRIPTION
**Pull request by jcarpe**
### What does this PR do?

Adds a small note on C++ standard lib dependencies when setting up bun.

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### CODE REVIEW

**Review by paperclover — CHANGES_REQUESTED** [review]
this is already covered in the troubleshooting section

> `### 'span' file not found on Ubuntu`

im re-reading this and it is a bit more verbose than it honestly needs to be. We should *move* that section up to where you put it, and probably make it a bit shorter so it isnt a hassle for non-ubuntu/debian users.

this way it will be harder to miss the instructions

**Comment by jcarpe** [comment]
@paperdave  Just to clarify - you're saying it is Ubuntu/Deb specific and therefor should be more discreet, but _in_ the contributing page?

Now that I am seeing the troubleshooting, I like the information better but interestingly never actually had the `'span" file not found` issue. It was more explicitly clang not finding the proper standard lib (`libstdc++` in my case).

**Comment by paperclover** [comment]
i think we should move that section up into where you added your note, and trim it down just a bit.

if you think it should be as long as it is, we can also put it in a details block.

```
{% details summary="For Ubuntu/Debian" %}

content

{% /details %}
```

I am 99% certain this situation is specific to the default configuration of Ubuntu.

**Comment by paperclover** [comment]
also want to note that both of these are in the contributing page

**Comment by jcarpe** [comment]
Ultimately I made it more wordy...

I reduced the content to a block quote inline that notes the standard library issue for Ubuntu and anchor linked down to the troubleshooting section. I then _added_ the Clang error that manifests for those who are simply running `bun setup` and getting the noted Clang error.

**Comment by paperclover** [comment]
thank you, i think this is good. ill merge once i double check this renders properly for the site (the doc site itself isnt public yet)

**Review by paperclover — APPROVED** [review]

**Comment by paperclover** [comment]
awesome

**Pull request merged**
