### PR TITLE
docs (runtime): the order of checking files when using bare impoort

### PR DESCRIPTION
**Pull request by DevinJohw**
### What does this PR do?

Changing the order of bare import. It should be `hello.tsx` > `hello.jsx` > `hello.ts` > `hello.mjs` > `hello.js` > `hello.cjs` > `hello.json` > `hello/index.tsx` > `hello/index.jsx` > `hello/index.ts` > `hello/index.mjs` > `hello/index.js` > `hello/index.cjs` > `hello/index.json`

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?

I have tested this on Replit. People can feeling the order by moving files into temp folder. Here's the link👇
https://replit.com/join/udtmgcymlc-devinjohw

### CODE REVIEW

**Comment by v3nntrnx** [comment]
If its really in that order then LGTM

**Comment by DevinJohw** [comment]
It's true, you can try it from my link.

https://replit.com/join/udtmgcymlc-devinjohw

**Comment by jumoog** [comment]
> It's true, you can try it from my link.
> 
> https://replit.com/join/udtmgcymlc-devinjohw

needs an account to try it 👎🏻

**Comment by DevinJohw** [comment]
Sorry, I can't think of other platform to run bun code that people can also check out and run publicly.🫠

**Comment by colinhacks** [comment]
Thanks!

**Pull request merged**
