### PR TITLE
fix(socket): fix `0.0.0.0` binding address

### PR DESCRIPTION
**Pull request by Hanaasagi**
### What does this PR do?

Close: #7355

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

existed tests.

### CODE REVIEW

**Comment by Hanaasagi** [comment]
Related to https://github.com/oven-sh/bun/pull/3758. I'm not sure why `0.0.0.0` is being changed to `null`; this causes even the use of `0.0.0.0` to bind to IPv6 `::`.

**Review by paperclover — CHANGES_REQUESTED** [review]
can you add a test specifically listening on 0.0.0.0 and then connecting over ipv6 and ensuring that the connect fails.

(or do you think that test would not be reliable?)

**Comment by Hanaasagi** [comment]
> can you add a test specifically listening on 0.0.0.0 and then connecting over ipv6 and ensuring that the connect fails.

Local tested this on Linux, and it works fine. Waiting the drawin ci results.

**Review by paperclover — APPROVED** [review]

**Comment by paperclover** [comment]
image

it seems some tests fail. the server in this case is listening on 0.0.0.0, but the connection is unclear what the default is. im not sure if this is a bad test (does node default to ipv6 in `new Socket`)

**Comment by Hanaasagi** [comment]
Good catch. I found that both Linux and Darwin failed in CI. But it worked fine on my local machine (Arch Linux). Need some time to investigate, I convert this to draft.

**Comment by Hanaasagi** [comment]
made a simple action test for this, when the server listens on 0.0.0.0, client connected without `hostname`, node will also use `::1`.

https://github.com/Hanaasagi/bun-ci-7366/actions/runs/7192177485/job/19588118516

**Review by paperclover — APPROVED** [review]

**Pull request merged**
