### PR TITLE
fix(bun install): Handle vercel and github tarball path dependencies

### PR DESCRIPTION
**Pull request by booniepepper**
### What does this PR do?

- fix(bun install): Handle vercel and github tarball path dependencies

Follows a similar approach (in this context) of [checking if a dependency is a tarball before checking github](https://github.com/pnpm/pnpm/blob/main/resolving/default-resolver/src/index.ts#L30-L35), and [filtering out repositories based on number of parts](https://github.com/pnpm/pnpm/blob/main/resolving/tarball-resolver/src/index.ts#L10)

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

- [x] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [x] I or my editor ran `zig fmt` on the changed files
- [ ] I included a test for the new code, or an existing test covers it
- [ ] JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed

### CODE REVIEW

**Comment by booniepepper** [comment]
Plan to add tests for these cases too, based on these two real-world dependencies:

```
"@vercel/turbopack-ecmascript-runtime": "https://gitpkg-fork.vercel.sh/vercel/turbo/crates/turbopack-ecmascript-runtime/js?turbopack-230922.2",
"when": "https://github.com/cujojs/when/tarball/1.0.2"
```

Both should be handled as tarballs

**Comment by booniepepper** [comment]
There's another test that could be added based on a real world dependency:

```
"@vercel/turbopack-ecmascript-runtime": "https://gitpkg-fork.vercel.sh/vercel/turbo/crates/turbopack-ecmascript-runtime/js?turbopack-230922.2"
```

but I'm observing that the HTTP request for this can be long (more than seconds)

**Review by dylan-conway — APPROVED** [review]
LGTM. I'll let the tests run and add the other test after

**Comment by dylan-conway** [comment]
Thanks!

**Comment by booniepepper** [comment]
Thanks too that was a blast!

**Comment by booniepepper** [comment]
> LGTM. I'll let the tests run and add the other test after

I added it here https://github.com/oven-sh/bun/pull/6190

**Pull request merged**
