### PR TITLE
Create github workflow to publish releases on dockerhub

### PR DESCRIPTION
**Pull request by Wulfre**
This will automatically make sure that changes to `dockerhub/Dockerfile` build successfully as well as publish new bun releases to DockerHub with semantic versioning tags `X`, `X.Y`, `X.Y.Z`, and `latest`.

Requires action secrets `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` to be set for the repo.

### CODE REVIEW

**Comment by alepouna** [comment]
@Jarred-Sumner I think that's something only you can add to the repo (unless there are more admins)

**Comment by pnodet** [comment]
@Wulfre @auroraisluna Sorry to bother, but isn't this already in the GitHub actions? [bun.yml](https://github.com/oven-sh/bun/blob/main/.github/workflows/bun.yml)

```yml
  release:
    runs-on: self-hosted
    needs: ["e2e"]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git -c submodule."src/bun.js/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j 8
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: jarredsumner
          password: ${{ secrets.DOCKERHUB_ALT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Pull Base Image
        run: bash .docker/pull.sh
      - name: Build release image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: release
          tags: |
            ghcr.io/jarred-sumner/bun:${{github.sha}}
            ghcr.io/jarred-sumner/bun:edge
            jarredsumner/bun:${{github.sha}}
            jarredsumner/bun:edge
          platforms: |
            linux/amd64
          labels: |
            org.opencontainers.image.title=bun
            org.opencontainers.image.description=bun is a fast bundler, transpiler, JavaScript Runtime environment and package manager for web software. The image is an Ubuntu 20.04 image with bun preinstalled into /opt/bun.
            org.opencontainers.image.vendor=bun
            org.opencontainers.image.source=https://github.com/oven-sh/bun
            org.opencontainers.image.url=https://bun.sh
          builder: ${{ steps.buildx.outputs.name }}
          push: true
```

**Comment by Wulfre** [comment]
@pnxdxt Jarred asked me to set this up in the discord.

It looks like the self-hosted runner that is supposed to handle that workflow isn't online or something like that. If you look at the log, all of the queued jobs timed out.

**Comment by pnodet** [comment]
@[Wulfre](https://github.com/Wulfre) Thanks for the explanation!

**Comment by pnodet** [comment]
Maybe we should delete the old self-hosted version at the same time?

**Comment by Wulfre** [comment]
The README should probably also be updated to recommend the `latest` tag, since the `edge` tag will be replaced by this.

**Pull request closed without merging**
