### PR TITLE
Set `fetch` timeout to 5 minutes

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

- Set the default timeout for `fetch` to 5 minutes instead of 60 seconds

### How did you verify your code works?

Existing tests

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
Fixes https://github.com/oven-sh/bun/issues/4799
Fixes https://github.com/oven-sh/bun/issues/5930

**Comment by remorses** [comment]
Why do you need a default timeout?

**Comment by Jarred-Sumner** [comment]
> Why do you need a default timeout?

Processes generally shouldn't hang forever. The timeout is not an absolute number, it is since the last time a message was received. You can disable the timeout for `fetch` with `timeout: false`

**Comment by empz** [comment]
> > Why do you need a default timeout?
> 
> Processes generally shouldn't hang forever. The timeout is not an absolute number, it is since the last time a message was received. You can disable the timeout for `fetch` with `timeout: false`

Sorry to post here, but where do you set this? 

```ts
Bun.fetch(url, {
  method: "POST",
  body: someBody,
  timeout: false // Typescript doesn't like
}
```
image


Is it a types problem and the argument actually works??

**Pull request merged**
