### PR TITLE
implement `bun update`

### PR DESCRIPTION
**Pull request by alexlamsl**
- analogous to `npm update`
- `bun update <name>` to refresh specified package under `package.json`
- `bun update` to refresh all package to latest versions

### What does this PR do?

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

- [x] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [x] I or my editor ran `zig fmt` on the changed files
- [x] I included a test for the new code, or an existing test covers it
- [ ] JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
Can you add a test with dependencies of dependencies that get updated? 

From reading the code, I'm a little confused why this works when the dependency is not passed in the list. Where does it choose to update the package? 

I'm also wondering how it deals with version tags like "latest", if those get updated. And if "*" is chosen.

**Comment by alexlamsl** [comment]
> From reading the code, I'm a little confused why this works when the dependency is not passed in the list. Where does it choose to update the package?

I'm assuming you meant `bun update` without any package names &minus; in which case `PackageManager.package_json_updates` would indeed an empty list, but since we've set `.to_update = true` we can differentiate this and mark all existing packages to be updated.

> I'm also wondering how it deals with version tags like "latest", if those get updated. And if "*" is chosen.

Same way as it would be handled by `bun install` without an existing lockfile, which is covered here IIRC:
https://github.com/oven-sh/bun/blob/f2f227720b3ffe1797a0a4e500e9a9a639167dc6/test/cli/install/bun-install.test.ts#L1228-L1288

> Can you add a test with dependencies of dependencies that get updated?

Will do 👌

**Comment by Jarred-Sumner** [comment]
We need to update zsh/fish/bash completions to add the `update` command.

**Comment by Jarred-Sumner** [comment]
Thank you

**Pull request merged**
