### PR TITLE
fix(install): Return NotSupported when errno == XDEV

### LINKED ISSUE #362: MacOS: Bun install throws errors on external volumes
image

Also note, but hopefully not relevant, I am running on a hackintosh

using `bun create next bun-next` on an external volume throws the following 

```
[package.json] Detected React - added "react-refresh"
[package.json] Detected Next.js

$ bun install
bun install v0.1.1
 Failed to install 23 packages
[13.00ms] done
error: Unexpected installing react-is
error: Unexpected installing object-assign
error: Unexpected installing js-tokens
error: Unexpected installing @next/swc-darwin-x64
error: Unexpected installing source-map-js
error: Unexpected installing picocolors
error: Unexpected installing nanoid
error: Unexpected installing caniuse-lite
error: Unexpected installing @next/env
error: Unexpected installing typescript
error: Unexpected installing react-refresh
error: Unexpected installing csstype
error: Unexpected installing @types/scheduler
error: Unexpected installing @types/prop-types
error: Unexpected installing @types/react
error: Unexpected installing bun-framework-next
error: Unexpected installing next
error: Unexpected installing react
error: Unexpected installing react-dom
error: Unexpected installing postcss
error: Unexpected installing styled-jsx
error: Unexpected installing loose-envify
error: Unexpected installing scheduler

[19.00ms] bun install


$ bun bun --use next
ResolveError can't find framework: "next".

Maybe it's not installed? Try running this:

   bun add -d bun-framework-next
   bun bun --use next
...
```

After reading docs, made sure `ulimit -n` was a ridiculous number and then installing:

```
/Volumes/Extras/websites/bun-next master
❯ ulimit -n           
2147483646

/Volumes/Extras/websites/bun-next master
❯ bun install --verbose
bun install v0.1.1
 Failed to install 23 packages
[7.00ms] done
Loaded 34 hoisted_packages
Loaded 47 resolutions
Loaded 47 dependencies
Loaded 4 extern_strings
Loaded 630 string_bytes
error: Unexpected installing react-is
error: Unexpected installing object-assign
error: Unexpected installing js-tokens
error: Unexpected installing @next/swc-darwin-x64
error: Unexpected installing source-map-js
error: Unexpected installing picocolors
error: Unexpected installing nanoid
error: Unexpected installing caniuse-lite
error: Unexpected installing @next/env
error: Unexpected installing typescript
error: Unexpected installing react-refresh
error: Unexpected installing csstype
error: Unexpected installing @types/scheduler
error: Unexpected installing @types/prop-types
error: Unexpected installing @types/react
error: Unexpected installing bun-framework-next
error: Unexpected installing next
error: Unexpected installing react
error: Unexpected installing react-dom
error: Unexpected installing postcss
error: Unexpected installing styled-jsx
error: Unexpected installing loose-envify
error: Unexpected installing scheduler
```

So after all of this, when I tried on MacOS's drive, it did work without issue

```
~
❯ bun create next bun-next
[package.json] Detected React - added "react-refresh"
[package.json] Detected Next.js

$ bun install
bun install v0.1.1
  🔍 Resolving [1/10] 
[52.00ms] git
 + @types/react@18.0.15
 + bun-framework-next@12.1.5
 + react-refresh@0.10.0
 + typescript@4.7.4
 + next@12.1.3
 + react@17.0.2
 + react-dom@17.0.2
 + react-is@17.0.2

 23 packages installed [538.00ms]
```

### PR DESCRIPTION
**Pull request by pan93412**
### What does this PR do?

When crossing the file system, the errno of `clonefile()` function is `.XDEV`.

This PR fixes it by returning `.XDEV` as `.NotSupported`.

Fixed #362

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

I test it manually. Looking for a way to test it automatically:

```
  ~/dev/Tmp/tt 5m 48s
base ❯ /Users/pan93412/dev-local/bun/packages/debug-bun-darwin-aarch64/bun-debug install
[SYS] read(3, 4096) = 4096 (0.354ms)
[SYS] close(3)
bun install v1.0.3_debug (0404d09c)
 + bun-types@1.0.2

 1 packages installed [27.00ms]
````

- [x] ~~I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be~~
- [x] I or my editor ran `zig fmt` on the changed files
- [ ] I included a test for the new code, or an existing test covers it
- [x] ~~JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed~~

### CODE REVIEW

**Comment by Electroid** [comment]
This is going to be hard to test automatically, and since this is a common issue we can land it now and figure that out later.

**Comment by ZeldOcarina** [comment]
@Electroid I am still getting the same error on 1.0.2, on which release will this be published on?

**Comment by Jarred-Sumner** [comment]
> @Electroid I am still getting the same error on 1.0.2, on which release will this be published on?

Please run `bun upgrade --canary` and give it a try.

**Comment by ZeldOcarina** [comment]
It works now cool!
It is similar to npm install as it just saves all packages in node_modules right?
Thank you!

**Comment by pan93412** [comment]
> It works now cool!
> It is similar to npm install as it just saves all packages in node_modules right?
> Thank you!

Yes.

**Pull request merged**
