### PR TITLE
Better types

### PR DESCRIPTION
**Pull request by colinhacks**
Merge in conjunction with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67827

---

### What does this PR do?

- Add `@types/node` as a dependency to `bun-types`. 
- Remove `no-default-lib`. 
- Make type declarations compatible with `lib.dom.d.ts` and `@types/node`

Possible breakages:

- This puts a *lot* of intermediate types into a namespace called `BunJS`. If a users depends on one of these (say, `BlobPart`) to be declared in the global scope, they will need to re-write it to `BunJS.BlobPart`
- If someone's code depends on the old declarations and isn't compatible with the official `@types/node` declarations, they may see TS compiler errors
- Without `no-default-lib`, anyone with `lib: ["dom"]` in their tsconfig.json will now see the DOM types reflected in their project. Currently bun-types is set up to *defer* to lib.dom.d.ts, so those declarations for, say, `Response` or `ReadableStream` effectively override Bun's.
- By extension, Bun overrides the declarations in `@types/node` for the following globals, but in most cases the declarations are identical.
   - Blob
   - Event
   - EventTarget
   - RequestInit
   - Request
   - ResponseInit
   - Response
   - FormData
   - Headers
   - File
   - performance
   - URL
   - URLSearchParams
   - TextDecoder
   - TextEncoder
   - BroadcastChannel
   - MessageChannel
   - MessagePort

### CODE REVIEW

**Comment by paperclover** [comment]
> BunJS.ResponseInit

Is this different from lib.dom.d.ts' `RequestInit` which is in the global scope?

Also, I don't really like *that* as the type namespace, because I feel like we dont want people to call the runtime "BunJS" as some already do, and this would push that further.

**Comment by paperclover** [comment]
Fixes #5134 and surely many more

**Comment by colinhacks** [comment]
> Is this different from lib.dom.d.ts' `RequestInit` which is in the global scope?


Oops bad example. `ResponseInit` is an interface and we declare it top-level. I updated to `BlobPart`...a union `type` that can't go top-level because it would conflict with `lib.dom.d.ts`. You can't have multiple `type` declarations with the same name but you can have multiple `interfaces` with the same name, as long as they're compatible.

> Also, I don't really like _that_ as the type namespace, because I feel like we dont want people to call the runtime "BunJS" as some already do, and this would push that further.

It can't be `Bun` because we `declare var Bun` already, and a `namespace` is a runtime construct. Open to other options here but nothing springs to mind.

**Comment by dsonet** [comment]
> > Is this different from lib.dom.d.ts' `RequestInit` which is in the global scope?
> 
> Oops bad example. `ResponseInit` is an interface and we declare it top-level. I updated to `BlobPart`...a union `type` that can't go top-level because it would conflict with `lib.dom.d.ts`. You can't have multiple `type` declarations with the same name but you can have multiple `interfaces` with the same name, as long as they're compatible.
> 
> > Also, I don't really like _that_ as the type namespace, because I feel like we dont want people to call the runtime "BunJS" as some already do, and this would push that further.
> 
> It can't be `Bun` because we `declare var Bun` already, and a `namespace` is a runtime construct. Open to other options here but nothing springs to mind.

What about just `bun`? Easier to type and recognize.

**Comment by paperclover** [comment]
Is there a reason it cant be imported from `bun` how it already is being done.

But also, i'm trying to figure out why namespaces can't be used. this snippet seems to declare all the types properly, but i may be missing something

image

if it's that `namespace Namespace` defines an empty object, that is fine, because the `Bun` global *does* exist as an object.

**Comment by colinhacks** [comment]
> But also, i'm trying to figure out why namespaces can't be used. this snippet seems to declare all the types properly, but i may be missing something

Ah, I'd been getting "Duplicate identifier" errors but they only show up when the namespace includes runtime constructs (makes sense).  Previously I'd been using `var` and `class` inside the `BunJS` namespace but the current approach is type-only so `Bun` will work after all. Cool.

> Is there a reason it cant be imported from bun how it already is being done.

It's kind of annoying to get these types out of the `module "bun"` when they're needed to declare globals. For instance:

```ts
declare module "bun" {
  // see the top of global.d.ts to see why this is conditional
  type _Response = "some conditional type..."
}

// doesn't work, must be a fully qualified name
interface Response extends import("bun")._Response;

// this breaks everything (can't have top-level imports)
import type {_Response} from "bun" 
interface Response extends _Response {};

// only way I'm aware of to make this work is "re-exporting" with a namespace
namespace Bun {
  type _Response = import("bun")._Response;
}
interface Response extends Bun.Response {}
```

I also think it's a decent goal to avoid a bunch of internal types being exported from the `"bun"` module. They'll show up in autocompletion when people are, say, writing out function parameter types. I think that's not ideal because there's a lot, they look intimidating, some are prefixed with `_`, it's rarely desirable. Putting them in a global namespace is cleaner imo.

**Pull request merged**
