### PR TITLE
Make bun docs searchable and easy to navigate

### PR DESCRIPTION
**Pull request by kimolalekan**
Link: https://bun-docs.vercel.app/

Features: 
- Navigation menu
- Sidebar navigation
- Search
- Light and Dark theme

### CODE REVIEW

**Comment by pnodet** [comment]
Awesome work!

Few ideas:
 • The link to docs from the `page.tsx` should redirect to `bun.sh/docs` rather than github
 • All your files should probably be located in the public folder since they are already built. IMO ideally the docs should be in a separate folder and only the index / css / other needed files be in the landing package. Could this be possible if we provide a path to docsify?
 • To allow hmr and dev on the landing, the `ssr.tsx` page should probably include something like :
 
 ```js
   if (req.url.endsWith("/docs")) {
    return new Response(file(join(import.meta.dir + "/public/", "docs/index.html")));
  }
  ```
  
  • I am not sure the licence, readme etc. are needed?

**Comment by michellbrito** [comment]
@kimolalekan Awesome work! We would want a separate repo for the docs https://github.com/oven-sh/docs. 

@Jarred-Sumner mentioned he wanted to use astro for the docs.

**Review by michellbrito — CHANGES_REQUESTED** [review]
@kimolalekan Awesome work! We would want a separate repo for the docs [oven-sh/docs](https://github.com/oven-sh/docs).

@Jarred-Sumner mentioned he wanted to use astro for the docs.

**Comment by kimolalekan** [comment]
@michellbrito I will setup the docs using Astro. 

Thanks

**Comment by kimolalekan** [comment]
@michellbrito https://github.com/oven-sh/docs Can't create a pull request cos the repo is empty.

**Comment by Tricked-dev** [comment]
> @michellbrito I will setup the docs using Astro.
> 
> Thanks

Hi you can use my repo as a starting point maybe I haven't put much time in actually organizing the docs but I see you have https://github.com/Tricked-dev/bun-docs

**Pull request closed without merging**
