### PR TITLE
Replace unmodified variable declarations with const

### PR DESCRIPTION
**Pull request by hustLer2k**
### What does this PR do?

There are a lot of declarations using var instead of const that are not mutated. Since Zig's build 0.12 (0.12.0-dev.1664+8ca4a5240) it is considered an error that prevents compilation.

This PR replaces unmodified variable declarations with const.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [✔️] Code changes

### How did you verify your code works?

- [✔️ ] I included a test for the new code, or an existing test covers it

### CODE REVIEW

**Comment by paperclover** [comment]
there is already a pr open that does this. and neither of them actually upgrade the version of zig to ensure that this issue doesn't happen again

**Comment by paperclover** [comment]
going to close in favor of the other pr/until we upgrade zig for real

**Comment by hustLer2k** [comment]
send a link pls

**Comment by hustLer2k** [comment]
is there already a zig upgrade PR in progress or i should take on the challenge? i've already resolved some of the other errors that prevent compilation

**Comment by paperclover** [comment]
there is not. i closed the other pr because it is equivilent to this.

i kind of want to wait until after the next release of bun to do the upgrade.

**Pull request closed without merging**
