### PR TITLE
Implement `bun start`

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

I don't know if we should ship this

This makes `bun start` work like `bun .`, except if there is a `server.js` or `server.ts` file, it will load that instead.

### CODE REVIEW

**Review by paperclover — APPROVED** [review]
cool so long as `bun start` can still run package.json start script, along with `bun start args to start script` also does that.

**Comment by remorses** [comment]
I don’t like adding 1 more command just to mimic npm, I have never seen someone using npm start to run server.js, most people also define a script with that name, I think it’s a legacy command no one uses anymore

**Comment by birkskyum** [comment]
It's starting to become confusing with all these overloaded names of standard package.json scripts/node conventions, like [bun dev](https://github.com/oven-sh/bun/issues/4166#issue-1851743731), [bun start](https://github.com/oven-sh/bun/pull/3910#issuecomment-1697661387), `bun test`, `bun build`, not to mention the overloaded [bun create](https://github.com/oven-sh/bun/issues/485), because these names are so canonical many people will assume they map directly to `bun run __` or `bun x create-__`, but they do something very different. If the overloads could be kept to a minimum I'm sure it would be appreciated.

**Comment by birkskyum** [comment]
- `bun build` "_bundle a project_", then maybe it should be called `bun bundle` which isn't overloaded
- `bun start` is longer then `bun .`, so it's really not needed. Also `bun` is both `node` and `npm`, and where `node start` is like `node .`, the `npm start` is like `npm run start`, so nobody moving from node/npm can intuitively tell what will happen when executing `bun start`, and not having it is thus a less ambiguous approach.
- `bun create` could be something like `generate`, `new`, `make`, `example`, `begin`.
Screenshot 2023-08-29 at 14 14 55

**Comment by Mouvedia** [comment]
The shorthand `npm start` should be matched by `bun start` which would alias `bun run start`.
**`npm start` and `npm test` are the most used shorthand scripts by far.**

If you do add `start` _for that purpose_ remember to add its less common counterparts, `restart` and `stop`, and their `pre/post` scripts.

**Comment by n7trd** [comment]
I agree with @birkskyum that it can become confusing.

I'd much rather run scripts with:
`bun run <script>` 
This approach makes the intend clear and obviates the need to remember any conflicting script names correlated to bun commands. It would be a lot clearer without reading advices like:

> If there is a name conflict between a package.json script and a built-in bun command (install, dev, upgrade, etc.) Bun's built-in command takes precedence. In this case, use the more explicit bun run command to execute your package script.

The confusion between `bun build` and `bun run build` is worth addressing. In my opinion, `bun bundle` aptly describes the action and is relatively less commonly used in package scripts, which works as an advantage.

Overall, I appreciate the ability to run (node) code without making changes to it. However, I don't believe this applies to the the CLI for me. They are distinct toolkits, and tweaking a few files to achieve your end goal doesn't seem too onerous. That's why I'm not entirely convinced by the bunx, which somewhat imitate node and tend to overlap with "bun create". But that's another matter altogether.

**Comment by Electroid** [comment]
We're not going to implement this now, we may revisit it later.

**Pull request closed without merging**
