### PR TITLE
feat(build): adjust arch linux auto detect to include manjaro

### PR DESCRIPTION
**Pull request by knightspore**
### What does this PR do?

Following on progress from issue #2664 and corresponding PR #6835, I noticed `bun setup` / `bun run build` were failing on a Manjaro machine for the same reason that Manjaro uses the same suffix as Arch for `libatomic`.

Currently, `CMakeLists.txt` looks for a `NAME` property in `/etc/os-release` matching `"Arch Linux"`. 

This PR introduces changes to the code to include matches for `"(Arch|Manjaro) Linux"`.
 
- [X] Code changes

### How did you verify your code works?

Re-built on Arch & Manjaro, read code in `CMakeLists.txt`.

### CODE REVIEW

**Comment by knightspore** [comment]
I force-pushed over the existing changes as for some reason git had diffed the entire file.

**Comment by tomByrer** [comment]
Thanks @knightspore; I was considering installing Manjaro on my desktop mostly to run Bun (laptop is Win)

**Review by paperclover — APPROVED** [review]

**Comment by paperclover** [comment]
for some reason cmakelists is CRLF, which results in your case being a full file diff.

i think that is my fault (happened during windows stuff). i will fix this at some point but it creates merge conflicts with anyone who has a pending change.

**Comment by paperclover** [comment]
for this, i'll merge after making sure ci doesnt somehow break

**Comment by knightspore** [comment]
thanks @paperdave, no worries - will keep an eye on CI in case there's anything I can fix up.

**Pull request merged**
