### PR TITLE
build: upgrade llvm to 16 to match zig 0.11.0

### PR DESCRIPTION
**Pull request by CGQAQ**
### What does this PR do?

* upgrade llvm to 16 to match zig 0.11.0
* the usocket version we depends on have some issues need to change  `UWS_CC_FLAGS` to ignore
```diff
- UWS_CC_FLAGS = -pthread  -DLIBUS_USE_OPENSSL=1 -DUWS_HTTPRESPONSE_NO_WRITEMARK=1  -DLIBUS_USE_BORINGSSL=1 -DWITH_BORINGSSL=1 -Wpedantic -Wall -Wextra -Wsign-conversion -Wconversion $(UWS_INCLUDE) -DUWS_WITH_PROXY
+ UWS_CC_FLAGS = -pthread  -DLIBUS_USE_OPENSSL=1 -DUWS_HTTPRESPONSE_NO_WRITEMARK=1  -DLIBUS_USE_BORINGSSL=1 -DWITH_BORINGSSL=1 -Wpedantic -Wall -Wextra -Wsign-conversion -Wconversion $(UWS_INCLUDE) -DUWS_WITH_PROXY -Wno-error=implicit-function-declaration -Wno-error=incompatible-function-pointer-types -Wno-error=implicit-int
```

- [x] [blocking PR](https://github.com/oven-sh/WebKit/pull/16)

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
oh nice

I think we also need to update JSC to use LLVM 16 before this can work too. Differing versions of LLVM with C++ tend to get weird allocation failures at runtime

**Comment by CGQAQ** [comment]
[this one](https://github.com/oven-sh/WebKit), main branch, right? I'll submit a PR there.

**Comment by Jarred-Sumner** [comment]
yeah

**Comment by CGQAQ** [comment]
[PR](https://github.com/oven-sh/WebKit/pull/16) submitted

**Comment by yisibl** [comment]
There are also several CI files that need to be updated.

e.g. https://github.com/oven-sh/bun/blob/557e912d9a9914bd1962ef632d146f760f5ffa39/.github/workflows/bun-mac-x64.yml#L175-L178

**Comment by Jarred-Sumner** [comment]
sorry haven't gotten to this

**Comment by Electroid** [comment]
We upgraded.

**Pull request closed without merging**
