### PR TITLE
ci: start running some of the citgm projects

### PR DESCRIPTION
**Pull request by nektro**
more to go but these are the ones that are already fully passing

should i make a status tracking issue for the rest upon merge?

### CODE REVIEW

**Comment by robobun** [comment]
@nektro, your commit d6a924db92e7b6b6a48e1a79ab1a47f022cf6fbc is building: [`#4377`](https://buildkite.com/bun/bun/builds/4377)

**Review by Electroid — CHANGES_REQUESTED** [review]
It's going to be better if this does not use another runner and is part of the existing test suite. A lot of stuff will not work, such as the error annotations or log previews.

**Comment by nektro** [comment]
> A lot of stuff will not work, such as the error annotations or log previews.

that's fine because the logs are short enough on their own and we still very easily see the binary pass/fail

**Comment by nektro** [comment]
the main benefit this initiative will provide is when we run into a situation where one of the projects have a test failure and we don't. then we can investigate and if there's a real bug there we then fix it and add it to our own suite

**Comment by nektro** [comment]
talked to @Electroid gonna rework this

**Pull request closed without merging**
