### PR TITLE
Fix import alias

### PR DESCRIPTION
**Pull request by zhiyuang**
fix https://github.com/oven-sh/bun/issues/1306

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
Can you add a test for this in transpiler.test?

**Comment by zhiyuang** [comment]
sure

**Comment by Jarred-Sumner** [comment]
You checked this runs in bun right? Bun escapes strings for JSC in complicated ways

**Comment by zhiyuang** [comment]
I checked by running `bun wiptest transpiler.test.js`. And `bun run index.js` for the simple situation mentioned in the issue.

**Pull request merged**
