### PR TITLE
`server.requestIp()`

### LINKED ISSUE #3540: Implement `server.requestIp`
```js
export default {
  async fetch(request, server) {
    return new Response(server.requestIp(request));
  }
}
```

### PR DESCRIPTION
**Pull request by Parzival-3141**
### What does this PR do?
Closes #3540
Implements `server.requestIp(request)`, returning the origin IP address of a Request. 

Currently it just returns an ipv6 address string directly from UWS. The plan is to return a "SocketAddress" object, which will contain the address string and a value signaling what type it is.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

- [x] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [x] I or my editor ran `zig fmt` on the changed files
- [ ] I included a test for the new code, or an existing test covers it
- [ ] JSValue used outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed

- [ ] I added TypeScript types for the new methods, getters, or setters

- [x] I ran `make codegen` to regenerate the C++ and Zig code

### CODE REVIEW

**Comment by phtdacosta** [comment]
Following the interoperability desire towards Node.js, would not it be better to offer the feature this way? @Jarred-Sumner
image

**Comment by simylein** [comment]
Any updates on this?

**Comment by JawadAhbab** [comment]
Any updates on this?

**Comment by phtdacosta** [comment]
Any...updates?

**Comment by ibnz36** [comment]
> Any...updates?

I guess there are other currently important issuess.. but I'd love this to get checked

**Pull request closed without merging**
