### PR TITLE
Fix lexer expected token error

### PR DESCRIPTION
**Pull request by zhiyuang**
fix https://github.com/oven-sh/bun/issues/1373

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
There are some cases with typescript where we don't want to return SyntaxError and stop the parsing

I think the bug is limited to the runtime and not the transpiler 

Maybe there are more places we should check for logs to have errors and halt execution in bun_js.zig?

**Comment by zhiyuang** [comment]
Ok, let me check it.

But how to explain this? It seems the output of `bun build` has accidentally add `test` after `test.`

SeaTalk_IMG_1666663288

**Comment by zhiyuang** [comment]
After investigating, find that logs in bun_js.zig has no errors, because `Bun__transpileFile`, `Bun__fetchBuiltinModule`, `Bun__*` these functions all have their own temp logger, not using global vm logger. So I add a check in `ModuleLoader.transpileSourceCode`.

**Comment by Jarred-Sumner** [comment]
Great, thank you

**Pull request merged**
