### PR TITLE
Upped the `MAX_HEADERS` value

### PR DESCRIPTION
**Pull request by TomHennessy**
### What does this PR do?

This ups the `MAX_HEADERS` value from `50` to `256`. 

This should be configurable but as a stop-gap I've upped the value so it doesn't cause some headers to drop off in large projects.

We have a large project that requires > 70 headers and currently this maximum value is a blocker to our migration.

I've left room for future-proofing reasons but long term it would be ideal to have this be configurable.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### CODE REVIEW

**Comment by TomHennessy** [comment]
Linked issue: https://github.com/oven-sh/bun/issues/6982

**Comment by Jarred-Sumner** [comment]
There's a couple more places that'll need to change.

In bindings.cpp, we assume a max of 50 headers. 

In http.zig, the client assumes some maximum of headers as well 

Also we should add a test that checks what happens if the client and server both send and receive 100 headers, to fully check it works

**Review by paperclover — CHANGES_REQUESTED** [review]
(see jarred's comments)

**Comment by TomHennessy** [comment]
Thanks both, I'll take a look when I can and get you something.

If it were to be configurable how would you want it to be structured?

**Pull request closed without merging**
