### PR TITLE
Fix minimum kernel version in docs

### PR DESCRIPTION
**Pull request by klatka**
### What does this PR do?

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### CODE REVIEW

**Comment by v3nntrnx** [comment]
LGTM

**Comment by colinhacks** [comment]
I think the current version is more correct, unless there are some show-stopping errors when using a pre-5.6 version?

**Comment by klatka** [comment]
> I think the current version is more correct, unless there are some show-stopping errors when using a pre-5.6 version?

We cannot say the minimum version is 5.1 and at the same time 5.1 - 5.5 **should** work.

**Review by paperclover — APPROVED** [review]

**Review by paperclover — CHANGES_REQUESTED** [review]
i think this should be worded as "recommended" because saying minimum is something then saying something below it also works is a contradiction.

**Review by paperclover — APPROVED** [review]
@colinhacks wdyt?

**Comment by colinhacks** [comment]
Went with "recommended minimum" lol

**Pull request merged**
