### PR TITLE
Run postinstall scripts in parallel

### LINKED ISSUE #606: Support npm lifecycle hook scripts
### What is the problem this feature will solve?

Many libraries currently depend on life cycle hooks for automated actions such as downloading a binary for a specific platform.

### What is the feature you are proposing to solve the problem?

Implement NPM's life-cycle hook scripts https://docs.npmjs.com/cli/v6/using-npm/scripts

### What alternatives have you considered?

n/a

### LINKED ISSUE #4549: Issue: Sharp fails when installing with bun
### What version of Bun is running?

1.0.0+5b9d8b87c41410091a7c602b895ad9ffda17819c

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

## Install Sharp

```shell
$ mkdir my-project && cd $_
$ bun init
$ bun install
$ bun add --exact sharp
$ mv index.ts index.js
```

## Code

```js
import sharp from "sharp";

const shield = sharp("shield.png");
const { width, height } = await shield.metadata();

console.log(await shield.metadata());
```

### What is the expected behavior?

Output next content:

```shell
{
  format: "png",
  width: 415,
  height: 415,
  space: "srgb",
  channels: 4,
  depth: "uchar",
  density: 72,
  isProgressive: false,
  hasProfile: false,
  hasAlpha: true,
  orientation: 1,
  exif: Buffer(80) [ 77, 77, 0, 42, 0, 0, 0, 8, 0, 2, 1, 18, 0, 3, 0, 0, 0, 1, 0, 1, 0, 0, 135, 105, 0, 4, 0, 0, 0, 1, 0, 0, 0, 38, 0, 0, 0, 0, 0, 3, 160, 1, 0, 3, 0, 0, 0, 1, 0, 1, 0, 0, 160, 2, 0, 4, 0, 0, 0, 1, 0, 0, 1, 159, 160, 3, 0, 4, 0, 0, 0, 1, 0, 0, 1, 159, 0, 0, 0, 0 ],
  xmp: Buffer(323) [ 60, 120, 58, 120, 109, 112, 109, 101, 116, 97, 32, 120, 109, 108, 110, 115, 58, 120, 61, 34, 97, 100, 111, 98, 101, 58, 110, 115, 58, 109, 101, 116, 97, 47, 34, 32, 120, 58, 120, 109, 112, 116, 107, 61, 34, 88, 77, 80, 32, 67, 111, 114, 101, 32, 54, 46, 48, 46, 48, 34, 62, 10, 32, 32, 32, 60, 114, 100, 102, 58, 82, 68, 70, 32, 120, 109, 108, 110, 115, 58, 114, 100, 102, 61, 34, 104, 116, 116, 112, 58, 47, 47, 119, 119, 119, 46, 119, 51, 46, 111, 114, 103, 47, 49, 57, 57, 57, 47, 48, 50, 47, 50, 50, 45, 114, 100, 102, 45, 115, 121, 110, 116, 97, 120, 45, 110, 115, 35, 34, 62, 10, 32, 32, 32, 32, 32, 32, 60, 114, 100, 102, 58, 68, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 32, 114, 100, 102, 58, 97, 98, 111, 117, 116, 61, 34, 34, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 120, 109, 108, 110, 115, 58, 116, 105, 102, 102, 61, 34, 104, 116, 116, 112, 58, 47, 47, 110, 115, 46, 97, 100, 111, 98, 101, 46, 99, 111, 109, 47, 116, 105, 102, 102, 47, 49, 46, 48, 47, 34, 62, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 60, 116, 105, 102, 102, 58, 79, 114, 105, 101, 110, 116, 97, 116, 105, 111, 110, 62, 49, 60, 47, 116, 105, 102, 102, 58, 79, 114, 105, 101, 110, 116, 97, 116, 105, 111, 110, 62, 10, 32, 32, 32, 32, 32, 32, 60, 47, 114, 100, 102, 58, 68, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 62, 10, 32, 32, 32, 60, 47, 114, 100, 102, 58, 82, 68, 70, 62, 10, 60, 47, 120, 58, 120, 109, 112, 109, 101, 116, 97, 62, 10 ]
}
```

### What do you see instead?

```shell
$ bun index.js                 
32 |     if (loadedModule) {
33 |       const [, loadedPackage] = loadedModule.match(/node_modules[\\/]([^\\/]+)[\\/]/);
34 |       help.push(`- Ensure the version of sharp aligns with the ${loadedPackage} package: "npm ls sharp"`);
35 |     }
36 |   }
37 |   throw new Error(help.join('\n'));
            ^
error: 
Something went wrong installing the "sharp" module

Cannot find module "../build/Release/sharp-darwin-x64.node" from "~/MyProjects/compose-images/node_modules/sharp/lib/sharp.js"

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-x64 runtime: "npm install --platform=darwin --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
      at ~/MyProjects/compose-images/node_modules/sharp/lib/sharp.js:37:8
      at globalThis (~/MyProjects/compose-images/node_modules/sharp/lib/sharp.js:37:33)
      at require (:1:20)
      at ~/MyProjects/compose-images/node_modules/sharp/lib/constructor.js:11:0
      at globalThis (~/MyProjects/compose-images/node_modules/sharp/lib/constructor.js:439:17)
      at require (:1:20)
      at ~/MyProjects/compose-images/node_modules/sharp/lib/index.js:6:6
      at globalThis (~/MyProjects/compose-images/node_modules/sharp/lib/index.js:16:17)
```

## Workaround

```shell
$ rm -rf node_modules bun.lockb
$ npm install
$ bun index.js
```

When using npm to install de dependencies it does not fail even while running with bun. Possible there is any missing feature in `bun install`?

I haven't tried with previous versions of Bun.

### LINKED ISSUE #4959: Fix `postinstall` and finish `trustedDependencies`
## 🔍 Summary

Bun introduces the concept of [`trustedDependencies`](https://bun.sh/docs/cli/install#trusted-dependencies), which allows you to specify an allow-list of packages that are allowed to run lifecycle scripts, such as `postinstall`. This is because dependencies can run arbitrary shell scripts when installed, and that's generally not great.

package.json:
```json
{
  "dependencies": {
    "utf-8-validate": "^6.0.3"
  },
  "trustedDependencies": [
    "utf-8-validate"
  ]
}
```

However, there are dependencies that you need to _trust_ to run scripts, because otherwise they do not work. To do this, you can add the package name to the `trustedDependencies` list in your package.json.

But doing this for every package would be annoying, so Bun would also have a default allow-list of the most popular packages on npm that need to run scripts, like utf-8-validate or esbuild. https://github.com/oven-sh/bun/pull/4263

We planned to include these changes in 1.0, but ran out of time. Once Bun supports these changes, you wouldn't need to use `trustedDependencies` for 99% of the time, except for more obscure dependencies. Also, when running `bun add` or `bun install`, there would be a prompt to indicate that the dependency is using scripts.

## 🚧 Workaround

1. Add package to `trustedDependencies` in your package.json.
```json
{
  "trustedDependencies": ["utf-8-validate"]
}
```

2. Run `bun remove`, then `bun add`, to ensure script is re-run.
```sh
bun remove utf-8-validate
bun add utf-8-validate
```

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

this runs postinstall scripts

Closes #606
Closes #4959
Closes #4549

### CODE REVIEW

**Comment by divmgl** [comment]
Closes https://github.com/oven-sh/bun/issues/4063
Closes https://github.com/oven-sh/bun/issues/2550

**Comment by ggobbe** [comment]
Closes #2022

**Comment by brianmhunt** [comment]
Noting the trivial patch https://github.com/oven-sh/bun/issues/4959#issuecomment-1804195244 that may help solve other cases noted in #4959

**Comment by Jarred-Sumner** [comment]
Closed by #7132

**Pull request closed without merging**
