### PR TITLE
Add crucial step make permanent bun on machines

### PR DESCRIPTION
**Pull request by miguelgargallo**
A group of friends and I, 15 developers in our free time at university, studying computer engineering, tried unsuccessfully to use Bun, we realized that many developers are missing the opportunity to use Bun, because after its installation, devs are unable to use Bun when they restart their machines, that's why we decided to support this amazing and nice project, bringing to open source, a crucial step, as it is: make permanent on your machine Bun. Currently Bun is missing the opportunity to be adopted by the masses by not incorporating this step in the guide, we hope and love Bun, that's why we bring this PR.

### CODE REVIEW

**Review by Kapsonfire — COMMENTED** [review]
whats wrong with
```
BUN_INSTALL="~/.bun"
PATH="$BUN_INSTALL/bin:$PATH"
```

and the installer tells you to do this

**Comment by miguelgargallo** [comment]
> 

Once I do that, the machine did not create the lines on the file, and I always need to do manually, I tried in 3 environments different locations, + university labs, and did not remind the commands.

**Comment by Kapsonfire** [comment]
you need to add it int he correct file
~/.profile
~./bashrc
~/.zshrc


depends on your shell you are using - after that you need to open new shell or read the file into the shell
```source ~/.bashrc```

**Comment by Electroid** [comment]
Thanks for working on this. Closing this out since we have a documentation [website](https://bun.sh/docs) now.

**Pull request closed without merging**
