### PR TITLE
fix(Request.body) allow Request body to be null

### PR DESCRIPTION
**Pull request by cirospaciari**
fixes https://github.com/oven-sh/bun/issues/1752

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
I think the behavior is that an empty response body is null, not that we need to track null specifically

**Comment by Jarred-Sumner** [comment]
so these variations should return null:

```
new Response(null).body
new Response().body
new Response(undefined).body
```

**Comment by Jarred-Sumner** [comment]
though hm this returns a ReadableStream:

```
new Response("").body
```

**Comment by cirospaciari** [comment]
> Member

And different of Response this also returns null:
`new Request("").body`

**Comment by Jarred-Sumner** [comment]
> > Member
> 
> And different of Response this also returns null: `new Request("").body`

yeah, interesting

**Pull request closed without merging**
