### PR TITLE
docs: Updated Bun.nanoseconds documentation

### PR DESCRIPTION
**Pull request by tomerh2001**
### What does this PR do?

Updated `Bun.nanoseconds` function documentation.

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

Closes https://github.com/oven-sh/bun/issues/9985

### CODE REVIEW

**Comment by tomerh2001** [comment]
https://github.com/oven-sh/bun/issues/9985

**Review by paperclover — CHANGES_REQUESTED** [review]
thanks for this pr, you've brought up something subtle but important.

> And is represented as a 64-bit unsigned integer

JavaScript does not have this data type, numbers larger than this will lose precision. This function is intended to wrap at (2^53 - 1) (Number.MAX_SAFE_INTEGER) to ensure that the number is always percise, but after inspecting the code further (BunObject.zig, fn nanoseconds), this code does not wrap.

> unless the counter is artificially manipulated

I don't think this counter can be artificially manipulated. `origin_timer` is shared by the logic for performance.now (which also starts losing precision after 14.8 weeks)

Overall, I think the documentation should be updated to say something along the lines of "this loses precision after 14.8 weeks, due to floating point behavior of numbers above Number.MAX_SAFE_INTEGER." not sure exactly how to word it.

(14.8 is derived from `Number.MAX_SAFE_INTEGER / (1e+9) / 60 / 60 / 24 / 7`)

**Comment by Jarred-Sumner** [comment]
(2^53) nanoseconds = 104.249991 days

**Comment by tomerh2001** [comment]
@paperdave @Jarred-Sumner 
Thanks for the input. I made another attempt at rewording the JSDoc; how about now?

**Review by paperclover — APPROVED** [review]
thanks. though now this function is now very documented in comparison to others that are much shorter / no doc comment. heh.

**Comment by tomerh2001** [comment]
> thanks. though now this function is now very documented in comparison to others that are much shorter / no doc comment. heh.
> 
This specifically troubled me since it hinted at a 14 weeks maximum value that wasn't explained

If I encounter similar issues I'll make sure to create additional PRs, also hopefully this'll encourage others to do the same :)

**Pull request merged**
