### PR TITLE
Implement `FormData`

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
This adds the [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) API as a global.

- [x] `multipart/form-data`
- [x] [`Response.prototype.formData()`](https://developer.mozilla.org/en-US/docs/Web/API/Response/formData)
- [x] [`Request.prototype.formData()`](https://developer.mozilla.org/en-US/docs/Web/API/Request/formData)
- [x] `application/x-www-form-urlencoded`
- [x] Bun.file() integration
- [x] Blob integration
- [x] `return new Response(myFormData)`

cc @kentcdodds

### CODE REVIEW

**Comment by kentcdodds** [comment]
You did all this last night!?

**Comment by Jarred-Sumner** [comment]
Only thing missing is `name` field in Blob.

**Comment by jimmywarting** [comment]
Amazing, could you share some lights into how this works under the hood in layman's terms?

- dose this use the actual formData decoder in WebKit or is it some custom implementation?
- what happens when really large file is being sent? are blob/files backed up by the filesystem and not in held in memory?
- i'm curios what part `Bun.file() integration` had a roll in this.

I'm only curious

**Comment by tomaszzmudzinski** [comment]
> Only thing missing is `name` field in Blob.

@Jarred-Sumner do you plan to add name field in the future?

**Comment by Jarred-Sumner** [comment]
@tomaszzmudzinski name field was added I think

**Pull request merged**
