### PR TITLE
ci: simplify build target labels so the name doesnt get cutoff

### PR DESCRIPTION
**Pull request by nektro**
before

image

after

image

### CODE REVIEW

**Comment by robobun** [comment]
@nektro, your commit 56f7665eefa8723128d5576cdf432102dbedd407 is building: [`#4282`](https://buildkite.com/bun/bun/builds/4282)

**Comment by Electroid** [comment]
The problem with removing those labels, is it makes the annotations ambigious for baseline/non-baseline

Screenshot 2024-10-03 at 8 46 22 AM

**Comment by nektro** [comment]
oh good eye, yeah thats not ideal
that seems like windows is using the wrong label then, because the macos failures look correct:

image

**Comment by nektro** [comment]
oh, no, i see the issue

**Comment by nektro** [comment]
fixed it

**Review by Electroid — APPROVED** [review]

**Pull request merged**
