### PR TITLE
fix syscall error handling

### LINKED ISSUE #4723: Bun & Docker issue
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Create a new SvelteKit app as outlined in the docs: https://bun.sh/guides/ecosystem/sveltekit

Create a `Dockerfile` like so:

```docker
FROM oven/bun:1.0

WORKDIR /app

COPY package.json .
COPY bun.lockb .

RUN bun install

COPY . .

# start app
CMD ["bun", "run", "dev"]
```

Create a `docker-compose.yml` for convenience:

```yaml
version: '3.8'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - '5173:5173'
``` 

Start the environment with `docker-compose up`

### What is the expected behavior?

Running in a docker container shouldn't produce errors, just like when you run it on the host machine. tldr, it works fine on the host but fails in a Dockerized environment with file descriptor issues.

### What do you see instead?

```bash
docker-compose up
[+] Running 1/1
 ⠿ Container my-app-ui-1  Recreated                                                                         0.5s
Attaching to my-app-ui-1
my-app-ui-1  | $ vite dev --host
my-app-ui-1  | 
my-app-ui-1  | Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /app): [EBADF] Bad file descriptor
my-app-ui-1  | undefined
my-app-ui-1  |    code: "EBADF"
my-app-ui-1  |  syscall: "fstat"
my-app-ui-1  |    errno: -9
my-app-ui-1  | 
my-app-ui-1  | Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /app): [EBADF] Bad file descriptor
my-app-ui-1  | undefined
my-app-ui-1  |    code: "EBADF"
my-app-ui-1  |  syscall: "fstat"
my-app-ui-1  |    errno: -9
my-app-ui-1  | 
my-app-ui-1  | Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /app): [EBADF] Bad file descriptor
my-app-ui-1  | undefined
my-app-ui-1  |    code: "EBADF"
my-app-ui-1  |  syscall: "fstat"
my-app-ui-1  |    errno: -9
my-app-ui-1  | 
my-app-ui-1  | Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /app): [EBADF] Bad file descriptor
my-app-ui-1  | undefined
my-app-ui-1  |    code: "EBADF"
my-app-ui-1  |  syscall: "fstat"
my-app-ui-1  |    errno: -9
my-app-ui-1  | 
my-app-ui-1  | 
my-app-ui-1  |   VITE v4.4.9  ready in 711 ms
my-app-ui-1  | 
my-app-ui-1  |   ➜  Local:   http://localhost:5173/
my-app-ui-1  |   ➜  Network: http://172.20.0.2:5173/
```

It appears to be have file descriptor errors trying to load a PostCSS config. I'm investigating where this comes from, but not familiar with SvelteKit/Vite generation of those files.   

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tobiaskohlbau**
Hello,

first of all I want to express that I'm new to bun. I've tried to built an SvelteKit application and ran into the same issue as #4723. Afterwards I jumped down deep into that rabbit hole :-D 

Fixes #4723

Possible related to some extend to one or more of #4671 #5935 #5943 #4896 #5306 #1446 

### What does this PR do?

The error handling between calling zig syscalls and using libc is different. Within zigs implementation, and therefore it's clone within bun, the return value of a syscall is of type usize. Libc implemenations use a signed integer namely c_int. As soon as libc is linked every response code of a syscall is interpreted via the libc errno function, but not every syscall is made through the libc interface. Only a few syscalls on aarch64 are used from libc every other one is called through zig itself. This could lead to errors beeing misinterpreted as success, cause its strictly positive and therefore not an error for the libc implementation. If an open syscall internally fails but is interpreted as a success the following write syscall would operate on a wrong file descriptor resulting in error bad file descriptor (EBADF).

### How did you verify your code works?

I've built a release version of bun and verified that the expected behaviour is observed.
Before that I've built a reproducer to force the bad behaviour.

1. Create a _index.ts_ with the below content.
2. Create a directory called test `mkdir test`
3. Run bun via `bun index.ts`
4. This should result in ISDIR error, cause the file gets opened an the syscall fails with _ERRISDIR_ but instead the open succeeds and the stat afterwards gets an _EBADF_.

# TypeScript reproducer

```TypeScript
import fs from "fs";
fs.writeFileSync(`test`, `hello world`);
```

The error from the second syscall is correctly interpreted as this is run on aarch64 and bun uses libc stat on aarch64.

https://github.com/oven-sh/bun/blob/6301778a589254e2c3c0d95f768fce303f528b03/src/sys.zig#L31-L50

## Before
```
# ./packages/bun-linux-aarch64/bun index.ts
1 | import fs from "fs";
2 | fs.writeFileSync(`test`, `hello world`);
   ^
EBADF: Bad file descriptor
    fd: "-21"
 syscall: "write"
   errno: -9

      at /home/user/tmp/bun/index.ts:2:0
```

## After
```
# ./packages/bun-linux-aarch64/bun index.ts
1 | import fs from "fs";
2 | fs.writeFileSync(`test`, `hello world`);
   ^
EISDIR: Is a directory
   path: "test"
 syscall: "open"
   errno: -21

      at /home/user/tmp/bun/index.ts:2:0
```

# Zig reproducer

```Zig
const std = @import("std");
const os = std.os;
const linux = os.linux;
const system = linux;
const builtin = @import("builtin");

pub fn main() !void {
    std.log.info("libc {}", .{builtin.link_libc});
    const rc_libc = system.openat(@as(system.fd_t, @intCast(-100)), "test", 321, 438);
    switch (os.errno(rc_libc)) {
        .SUCCESS => std.log.info("success", .{}),
        .ISDIR => std.log.info("is directory", .{}),
        else => return,
    }

    const rc_linux = system.openat(@as(system.fd_t, @intCast(-100)), "test", 321, 438);
    switch (linux.getErrno(rc_linux)) {
        .SUCCESS => std.log.info("success", .{}),
        .ISDIR => std.log.info("is directory", .{}),
        else => return,
    }
}
```

## Output after building with _zig build-exe main.zig_
```
info: libc false
info: is directory
info: is directory
```

## Output after building with _zig build-exe main.zig --library c_
```
info: libc true
info: success
info: is directory
```

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
Thank you very much for this and for the write-up

I suspect this change should only be applied on Linux aarch64 and not on Linux x64. But there should be some extra test failures in a few places if that's true (there are also a handful of test failures in CI right now, but these ones should have to do with error messages)

**Comment by tobiaskohlbau** [comment]
> Thank you very much for this and for the write-up
> 
> I suspect this change should only be applied on Linux aarch64 and not on Linux x64. But there should be some extra test failures in a few places if that's true (there are also a handful of test failures in CI right now, but these ones should have to do with error messages)

As far as I understand shouldn't the following type switch handle both sys call interfaces and it's response types, either on aarch64 or x64 (usize vs c_int). That's my reason to only remove it instead of checking the architecture at comptime. I'm new to zig too, but is the type assertion (`@TypeOf`) comptime evaluated?

https://github.com/oven-sh/bun/blob/6301778a589254e2c3c0d95f768fce303f528b03/src/sys.zig#L259-L262


Thanks for your response, please let me know if any changes are required.

**Comment by Hanaasagi** [comment]
I think the meaning of `use_libc` is somewhat ambiguous. It only represents that some syscalls use functions from libc, such as `stat` on aarch64. However, we use this boolean value in a more generic `getErrno` function to handle the return values of every syscall.

https://github.com/oven-sh/bun/blob/6301778a589254e2c3c0d95f768fce303f528b03/src/sys.zig#L23-L24

https://github.com/oven-sh/bun/blob/6301778a589254e2c3c0d95f768fce303f528b03/src/sys.zig#L247-L256


`openatOSPath` is implemented directly through syscall on Linux but via `openat` on macOS.

https://github.com/oven-sh/bun/blob/6301778a589254e2c3c0d95f768fce303f528b03/src/sys.zig#L398-L420

In the `getErrno` function, the `use_libc` variable differs across these three platforms:

- Linux x86_64: `use_libc = false`
- macOS: `use_libc = true`
- aarch64: `use_libc = true`

Both aarch64 and macOS have `use_libc` set to true, but aarch64 uses syscall, while macOS uses `openat`. This leads to correct behavior on macOS but incorrect behavior on aarch64.

**Comment by tobiaskohlbau** [comment]
What you're stating is correct, I've tried to say the same within the commit message itself 😅 Looks like it was not as clear.

**Comment by tobiaskohlbau** [comment]
@Electroid I've seen you've merged the main into this. I'm unsure what to do from here, please let me know if the PR itself needs some update. I'm more than willing to get this over the finish line.

**Comment by tarruda** [comment]
This will also close #4627 and #5820

This is an integer cast error which is deep into the error handling of multiple fs functions and will likely fix many Linux/arm64 issues. Would be a good idea to enable CI tests for Linux/arm64 after this is merged

**Comment by Jarred-Sumner** [comment]
Closing in favor of https://github.com/oven-sh/bun/pull/6942

**Pull request closed without merging**
