### PR TITLE
feat: Make using `await` inside a non-async function have a helpful error message

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

Comparison:

image

Also:
- Adds `notes` as a getter on`BuildMessage`
- Frees the `notes` slice in `deinit`

### How did you verify your code works?

There are tests. Most of the parser changes were based on what esbuild does.

### CODE REVIEW

**Comment by paperclover** [comment]
i broke `test/napi/napi.test.ts` on the windows branch.

this seems to be flaky with test timeout. cc @dylan-conway
image

**Review by paperclover — APPROVED** [review]
great

**Review by paperclover — CHANGES_REQUESTED** [review]
can we fix this test case:
```
() => {
  await 1;
};
```

**Comment by Jarred-Sumner** [comment]
~no~ let's fix in a follow-up

**Pull request merged**
