### PR TITLE
Update default-trusted-dependencies.txt

### PR DESCRIPTION
**Pull request by balazsorban44**
### What does this PR do?

`bunx auth` should not fail for [`auth`](https://npm.im/auth). Currently, it throws
> error: Failed to run "auth" due to error InvalidExe

Which I traced down to this file. Let me know if this is right! There is no postinstall scripts, see https://www.npmjs.com/package/auth?activeTab=code

This works fine with `pnpx auth`

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
Trusted dependencies are for lifecycle scripts in package.json and do nothing for packages without lifecycle scripts

This sounds like a different bug, like maybe we are not marketing the executable file as executable (chmod +x)

**Comment by ndom91** [comment]
Anecdotally, on my machine `bunx auth` does download the package to `/tmp/auth@latest--bunx` and the `node_modules` there contain a `.bin/auth` which has the executable bit set and is symlinked to `../auth/index.js` (which does exist) :thinking:

**Comment by Jarred-Sumner** [comment]
Ah, this is a different bug

There's no shebang at the top of the file

and we currently assume files without extensions in the filename have some kind of shebang

image

**Comment by balazsorban44** [comment]
Thanks for the :fire: reply! Adding a shebang fixed it! `bunx auth` :relieved: :heavy_check_mark:

**Pull request closed without merging**
