### PR TITLE
Fix missing "readable" events

### PR DESCRIPTION
**Pull request by heimskr**
### What does this PR do?

Fixes an issue where depending on the size of a file opened with `fs.createReadStream`, a final `readable` event (during which `.read()` returns `null`) can be mistakenly not emitted. This causes, for example, `prisma init` to exit without doing anything.

- [ ] Documentation or TypeScript types
- [x] Code changes

### How did you verify your code works?

I added some tests to `/test/js/node/stream/node-stream.test.js` and I also ran `bun --bun x prisma init`.

### CODE REVIEW

**Comment by robobun** [comment]
@heimskr, your commit 0cab72634faa43d432e87f7e6ea60da595234acb is building: [`#7505`](https://buildkite.com/bun/bun/builds/7505)

**Review by Jarred-Sumner — CHANGES_REQUESTED** [review]
Tests with hardcoded delays are either optimistically flaky or pessimistically slow by design. We should avoid adding hardcoded delays as much as we can.

When you write a test with a hardcoded amount of time to delay, ask yourself "is there a more specific source of truth we could use?"

We aren't trying to wait 20ms. We are trying to wait until both the `"close"` and the `"readable"` events are emitted. So, let's do that.

**Comment by heimskr** [comment]
> We aren't trying to wait 20ms. We are trying to wait until both the `"close"` and the `"readable"` events are emitted. So, let's do that.

My fear is that eventually some future regression might cause either event to not be emitted, in which case the test would never complete. How should I handle this?

**Comment by Jarred-Sumner** [comment]
> My fear is that eventually some future regression might cause either event to not be emitted, in which case the test would never complete. 

The test will timeout and we will see it in CI

**Pull request merged**
