### PR TITLE
Installing unzip.

### PR DESCRIPTION
**Pull request by AbdullahOB**
### What does this PR do?

This change is for Developers documentation, so it informs the developers that they need to install unzip before installing bun.

- [X] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### CODE REVIEW

**Comment by v3nntrnx** [comment]
It says native but apt is only for debian

**Comment by AbdullahOB** [comment]
I've tried it on WSL and it didn't run the install before I installed the unzip package for wsl.

**Comment by v3nntrnx** [comment]
> I've tried it on WSL and it didn't run the install before I installed the unzip package for wsl.

What I am trying to say is, `apt`/`apt-get` is not available on MacOS and other Linux distributions than Debian. It says "native" one line prior

**Comment by AbdullahOB** [comment]
> > I've tried it on WSL and it didn't run the install before I installed the unzip package for wsl.
> 
> What I am trying to say is, `apt`/`apt-get` is not available on MacOS and other Linux distributions than Debian. It says "native" one line prior

Yes I understand, thank you for clarifiying I will perform edits on the commit.

**Comment by AbdullahOB** [comment]
I've added for both CentOS/RHEL and Debian/Ubuntu, i think this would be more clear.

**Comment by Electroid** [comment]
We want to make these install commands concise, will keep as-is for now.

**Pull request closed without merging**
