### PR TITLE
feat: new blank template

### PR DESCRIPTION
**Pull request by xhyrom**
I created this simple template when people want to start from scratch so that they at least have `package.json`

### CODE REVIEW

**Comment by vizn3r** [comment]
i like this one

**Review by vizn3r — APPROVED** [review]
good

**Comment by devdeem** [comment]
cool xd

**Review by ghost — APPROVED** [review]
Looks fine!

**Review by gi-dellav — APPROVED** [review]

**Review by icarusgk — APPROVED** [review]
A nice starter blank template. ⚡

**Comment by Jarred-Sumner** [comment]
@xHyroM Thank you for this.

Can you add a tsconfig.json file with `bun-types` and `bun-types` as a dependency?

**Comment by xhyrom** [comment]
> @xHyroM Thank you for this.
> 
> Can you add a tsconfig.json file with `bun-types` and `bun-types` as a dependency?

done

**Pull request merged**
